/**
 *
 *
 */

#include "edginc/config.hpp"
#include "edginc/DefaultConstructor.hpp"
#include "edginc/GenericSensitivityFactory.hpp"
#include "edginc/IResultsFunction.hpp"
#include "edginc/Additive.hpp"
#include "edginc/RiskProperty.hpp"
#include "edginc/IScalarDerivative.hpp"
#include "edginc/ScalarRiskPropertySensitivity.hpp"
#include "edginc/CRSpotVolParallel.hpp"

DRLIB_BEGIN_NAMESPACE

const double ONE_BASIS_POINT = 0.0001;

/**
 * Calculates derivative of instrument price w.r.t. bulk shifts in
 * the mean reversion
 *
 * The output generated by this sensitivity is:
 * <DL>
 * <DT>CR_MEAN_REVERSION_PARALLEL 
 * <DD>Change in price when the mean reversion is shifted up by 1bp
 * </DL>
 *
 * The derivative is reported in 20%-units, i.e. the value reported is 
 * 5 times smaller than the actual partial derivative.
 */

class CRSpotVegaParallel: public ScalarRiskPropertySensitivity,
                               public virtual Additive {

    static void load(CClassSP& clazz) {
        clazz->setPublic();
        REGISTER(CRSpotVegaParallel, clazz);
        IMPLEMENTS(Additive);
        SUPERCLASS(ScalarRiskPropertySensitivity);
        EMPTY_SHELL_METHOD(&DefaultConstructor<CRSpotVegaParallel>::iObject);
        SensitivityFactory::addSens(NAME,
                                    new GenericSensitivityFactory<CRSpotVegaParallel>(), 
                                    new CRSpotVegaParallel(DEFAULT_SHIFT),
                                    ITweakableWithRespectTo<CRSpotVolParallel>::TYPE);
    }

    ScalarRiskPropertySensitivity::Deriv deriv() const {
        return Deriv(IResultsFunction::price(),
                     RiskProperty<CRSpotVolParallel>::SP(),
                     IScalarDerivative::oneSided(),
                     ONE_BASIS_POINT);
    }

public:

    static CClassConstSP const TYPE;

    static const double DEFAULT_SHIFT;
    static const string NAME;

    CRSpotVegaParallel(double shiftSize = DEFAULT_SHIFT):
        ScalarRiskPropertySensitivity(TYPE, NAME, shiftSize)
    {}
};

const string CRSpotVegaParallel::NAME = "CR_SPOT_VEGA_PARALLEL";
const double CRSpotVegaParallel::DEFAULT_SHIFT = 100 * ONE_BASIS_POINT;

CClassConstSP const CRSpotVegaParallel::TYPE = CClass::registerClassLoadMethod(
    "CRSpotVegaParallel", typeid(CRSpotVegaParallel), load);

/**
   Included in RiskMgrLib::linkInClasses() to force linkage into the Windows
   exe.
 */
bool CRSpotVegaParallelLinkIn() {
    return CRSpotVegaParallel::TYPE != NULL;
}

DRLIB_END_NAMESPACE
