/**
 *
 *
 */

#include "edginc/config.hpp"
#include "edginc/DefaultConstructor.hpp"
#include "edginc/GenericSensitivityFactory.hpp"
#include "edginc/IResultsFunction.hpp"
#include "edginc/Additive.hpp"
#include "edginc/RiskProperty.hpp"
#include "edginc/IScalarDerivative.hpp"
#include "edginc/ScalarRiskPropertySensitivity.hpp"
#include "edginc/IRMeanReversionParallelProperty.hpp"

DRLIB_BEGIN_NAMESPACE

const double ONE_BASIS_POINT = 0.0001;

/**
 * Calculates derivative of instrument price w.r.t. bulk shifts in
 * the mean reversion
 *
 * The output generated by this sensitivity is:
 * <DL>
 * <DT>CR_MEAN_REVERSION_PARALLEL 
 * <DD>Change in price when the mean reversion is shifted up by 1bp
 * </DL>
 *
 * The derivative is reported in 20%-units, i.e. the value reported is 
 * 5 times smaller than the actual partial derivative.
 */

class IRMeanReversionParallel: public ScalarRiskPropertySensitivity,
                               public virtual Additive {

    static void load(CClassSP& clazz) {
        clazz->setPublic();
        REGISTER(IRMeanReversionParallel, clazz);
        IMPLEMENTS(Additive);
        SUPERCLASS(ScalarRiskPropertySensitivity);
        EMPTY_SHELL_METHOD(&DefaultConstructor<IRMeanReversionParallel>::iObject);
        SensitivityFactory::addSens(NAME,
                                    new GenericSensitivityFactory<IRMeanReversionParallel>(), 
                                    new IRMeanReversionParallel(DEFAULT_SHIFT),
                                    ITweakableWithRespectTo<IRMeanReversionParallelProperty>::TYPE);
    }

    ScalarRiskPropertySensitivity::Deriv deriv() const {
        return Deriv(IResultsFunction::price(),
                     RiskProperty<IRMeanReversionParallelProperty>::SP(),
                     IScalarDerivative::oneSided(),
                     0.1); // Requirement: 10%
    }

public:

    static CClassConstSP const TYPE;

    static const double DEFAULT_SHIFT;
    static const string NAME;

    IRMeanReversionParallel(double shiftSize = DEFAULT_SHIFT):
        ScalarRiskPropertySensitivity(TYPE, NAME, shiftSize)
    {}
};

const string IRMeanReversionParallel::NAME = "IR_MEAN_REVERSION_PARALLEL";
const double IRMeanReversionParallel::DEFAULT_SHIFT = -0.1; // Requirement: -10%

CClassConstSP const IRMeanReversionParallel::TYPE = CClass::registerClassLoadMethod(
    "IRMeanReversionParallel", typeid(IRMeanReversionParallel), load);

/**
   Included in RiskMgrLib::linkInClasses() to force linkage into the Windows
   exe.
 */
bool IRMeanReversionParallelLinkIn() {
    return IRMeanReversionParallel::TYPE != NULL;
}

DRLIB_END_NAMESPACE
