
double FX_Volatility_dk3f_dupire(DKMaille<double> &dVolStripDates,
                                 double dDomesticStdDev,
                                 double dForeignStdDev,
                                 double dSpotFXVol,
                                 double dDomesticMeanReversion,
                                 double dForeignMeanReversion,
                                 double dCorrelationSpotFXDomestic,
                                 double dCorrelationSpotFXForeign,
                                 double dCorrelationForeignDomestic,
                                 DKMaille<double> &dSpotFXDates,
                                 DKMaille<double> &dSpotFXVols,
                                 double dFlatOrTimeDependent);




double TreeDK3F_FX_OPTION(int no_of_steps_per_year, 
                          int spot_date, 
                          int no_of_ratesBase, 
                          int no_of_ratesForeign, 
                          DKMaille<double> dateBase, 
                          DKMaille<double> rateBase, 
                          DKMaille<double> dateForeign, 
                          DKMaille<double> rateForeign, 
                          double smileBase, 
                          double smileForeign,
                          int no_of_targetdates, 
                          DKMaille<double> targetdates, 
                          double dVolatilityChoice,
                          double dBetaBase,
                          double dSigma1Base,
                          double dSigma2Base,
                          double dBetaForeign,
                          double dSigma1Foreign,
                          double dSigma2Foreign,
                          double dCorrBaseForeign,
                          double dFXForeignCorrelation,
                          double dFXVolatility,
                          double dFXDomesticCorrelation,
                          double dSpotFX,
                          double dStrike,
                          double dCallPut,
                          DKMaille<double> dSpotFXDates,
                          DKMaille<double> dSpotFXVols,
                          double dFlatOrTimeDependent,
													double dOptionType,
                          DKMaille<double> &dOutput);



double TreeDK3F_CALLABLE_FX_BOOSTER(int no_of_steps_per_year, 
                                    int spot_date, 
                                    int no_of_ratesBase, 
                                    int no_of_ratesForeign, 
                                    DKMaille<double> dateBase, 
                                    DKMaille<double> rateBase, 
                                    DKMaille<double> dateForeign, 
                                    DKMaille<double> rateForeign, 
                                    int no_of_targetdates, 
                                    DKMaille<double> targetdates, 
                                    DKMaille<double> strikes,
                                    DKMaille<double> notionals,
                                    DKMaille<double> funding,
                                    DKMaille<double> capstrikes,
                                    DKMaille<double> fundingaccruals,
                                    DKMaille<double> fxcouponaccruals,
                                    double dVolatilityChoice,
                                    double dBetaBase,
                                    double dSigma1Base,
                                    double dSigma2Base,
                                    double smileBase, 
                                    double dBetaForeign,
                                    double dSigma1Foreign,
                                    double dSigma2Foreign,
                                    double smileForeign,
                                    double dCorrBaseForeign,
                                    double dFXForeignCorrelation,
                                    double dFXVolatility,
                                    double dFXDomesticCorrelation,
                                    double dSpotFX,
                                    double dFXFixing,
                                    double dFinalExchange,
                                    double dFinalExchangeFX,
                                    double dSmoothing,
                                    double dCallPut,
                                    double dLongShort,
                                    DKMaille<double> dSpotFXDates,
                                    DKMaille<double> dSpotFXVols,
                                    double dFlatOrTimeDependent,
                                    DKMaille<double> &dOutput);


double TreeDK3F_CALLABLE_COUPON(int no_of_steps_per_year, 
																int spot_date, 
																int no_of_ratesBase, 
																int no_of_ratesForeign, 
																DKMaille<double> dateBase, 
																DKMaille<double> rateBase, 
																DKMaille<double> dateForeign, 
																DKMaille<double> rateForeign, 
																int no_of_targetdates, 
																DKMaille<double> targetdates, 
																DKMaille<double> strikes,
																DKMaille<double> notionals,
																double dVolatilityChoice,
																double dBetaBase,
																double dSigma1Base,
																double dSigma2Base,
																double smileBase,
																double dBetaForeign,
																double dSigma1Foreign,
																double dSigma2Foreign,
																double smileForeign,
																double dCorrBaseForeign,
																double dFXForeignCorrelation,
																double dFXVolatility,
																double dFXDomesticCorrelation,
																double dSpotFX,
																double dLongShort,
																DKMaille<double> dSpotFXDates,
																DKMaille<double> dSpotFXVols,
																double dFlatOrTimeDependent,
																DKMaille<double> &dOutput);
