#ifndef ARM_XL_REV_LOCAL_H
#define ARM_XL_REV_LOCAL_H


__declspec(dllexport) LPXLOPER WINAPI Local_REVERSE (LPXLOPER XL_structSwapLeg,
													 LPXLOPER XL_classSwapLeg,
													 LPXLOPER XL_receiveOrPay,
													 LPXLOPER XL_coupon,
													 LPXLOPER XL_exe,
													 LPXLOPER XL_redemp,
													 LPXLOPER XL_classRedemp,
													 LPXLOPER XL_dualDate,
													 LPXLOPER XL_dualStrike,
													 LPXLOPER XL_dualFlag);
__declspec(dllexport) LPXLOPER WINAPI Local_PXL_REVERSE (LPXLOPER XL_structSwapLeg,
														 LPXLOPER XL_classSwapLeg,
														 LPXLOPER XL_receiveOrPay,
														 LPXLOPER XL_coupon,
														 LPXLOPER XL_exe,
														 LPXLOPER XL_redemp,
														 LPXLOPER XL_classRedemp,
														 LPXLOPER XL_dualDate,
														 LPXLOPER XL_dualStrike,
														 LPXLOPER XL_dualFlag);

__declspec(dllexport) LPXLOPER WINAPI Local_STRUCTREVERSECOUPON(LPXLOPER XL_date,
																LPXLOPER XL_strike,
																LPXLOPER XL_power,
																LPXLOPER XL_callput,
																LPXLOPER XL_xo,
																LPXLOPER XL_floor,
																LPXLOPER XL_cap);
__declspec(dllexport) LPXLOPER WINAPI Local_PXL_STRUCTREVERSECOUPON(LPXLOPER XL_date,
																	LPXLOPER XL_strike,
																	LPXLOPER XL_power,
																	LPXLOPER XL_callput,
																	LPXLOPER XL_xo,
																	LPXLOPER XL_floor,
																	LPXLOPER XL_cap);

__declspec(dllexport) LPXLOPER WINAPI Local_REVERSE_CALENDAR (LPXLOPER XL_structSwapLeg,
															  LPXLOPER XL_classSwapLeg,
															  LPXLOPER XL_receiveOrPay,
															  LPXLOPER XL_coupon,
															  LPXLOPER XL_exe,
															  LPXLOPER XL_redemp,
															  LPXLOPER XL_classRedemp,
															  LPXLOPER XL_dualDate,
															  LPXLOPER XL_dualStrike,
															  LPXLOPER XL_dualFlag,
															  LPXLOPER XL_dStartDates,
															  LPXLOPER XL_dEndDates,
															  LPXLOPER XL_dFixingDates,
															  LPXLOPER XL_dPaymentDates,
															  LPXLOPER XL_fStartDates,
															  LPXLOPER XL_fEndDates,
															  LPXLOPER XL_fFixingDates,
															  LPXLOPER XL_fPaymentDates);
__declspec(dllexport) LPXLOPER WINAPI Local_PXL_REVERSE_CALENDAR (LPXLOPER XL_structSwapLeg,
																  LPXLOPER XL_classSwapLeg,
																  LPXLOPER XL_receiveOrPay,
																  LPXLOPER XL_coupon,
																  LPXLOPER XL_exe,
																  LPXLOPER XL_redemp,
																  LPXLOPER XL_classRedemp,
																  LPXLOPER XL_dualDate,
																  LPXLOPER XL_dualStrike,
																  LPXLOPER XL_dualFlag,
																  LPXLOPER XL_dStartDates,
																  LPXLOPER XL_dEndDates,
																  LPXLOPER XL_dFixingDates,
																  LPXLOPER XL_dPaymentDates,
																  LPXLOPER XL_fStartDates,
																  LPXLOPER XL_fEndDates,
																  LPXLOPER XL_fFixingDates,
																  LPXLOPER XL_fPaymentDates);

__declspec(dllexport) LPXLOPER WINAPI Local_REVERSENOTIONAL_CALENDAR (LPXLOPER XL_structSwapLeg,
																	  LPXLOPER XL_classSwapLeg,
																	  LPXLOPER XL_receiveOrPay,
																	  LPXLOPER XL_coupon,
																	  LPXLOPER XL_exe,
																	  LPXLOPER XL_redemp,
																	  LPXLOPER XL_classRedemp,
																	  LPXLOPER XL_dualDate,
																	  LPXLOPER XL_dualStrike,
																	  LPXLOPER XL_dualFlag,
																	  LPXLOPER XL_dStartDates,
																	  LPXLOPER XL_dEndDates,
																	  LPXLOPER XL_dFixingDates,
																	  LPXLOPER XL_dPaymentDates,
																	  LPXLOPER XL_fStartDates,
																	  LPXLOPER XL_fEndDates,
																	  LPXLOPER XL_fFixingDates,
																	  LPXLOPER XL_fPaymentDates);
__declspec(dllexport) LPXLOPER WINAPI Local_PXL_REVERSENOTIONAL_CALENDAR (LPXLOPER XL_structSwapLeg,
																		  LPXLOPER XL_classSwapLeg,
																		  LPXLOPER XL_receiveOrPay,
																		  LPXLOPER XL_coupon,
																		  LPXLOPER XL_exe,
																		  LPXLOPER XL_redemp,
																		  LPXLOPER XL_classRedemp,
																		  LPXLOPER XL_dualDate,
																		  LPXLOPER XL_dualStrike,
																		  LPXLOPER XL_dualFlag,
																		  LPXLOPER XL_dStartDates,
																		  LPXLOPER XL_dEndDates,
																		  LPXLOPER XL_dFixingDates,
																		  LPXLOPER XL_dPaymentDates,
																		  LPXLOPER XL_fStartDates,
																		  LPXLOPER XL_fEndDates,
																		  LPXLOPER XL_fFixingDates,
																		  LPXLOPER XL_fPaymentDates);

__declspec(dllexport) LPXLOPER WINAPI Local_ARM_POWERREVERSE (LPXLOPER XL_initPeriodLeg,
															  LPXLOPER XL_realFundLeg,
															  LPXLOPER XL_fxUnderLeg,
															  LPXLOPER XL_fxNumLeg,
															  LPXLOPER XL_noticeDates,
															  LPXLOPER XL_cancelDates,
															  LPXLOPER XL_FX0,
															  LPXLOPER XL_fxStep,
															  LPXLOPER XL_capValue,
															  LPXLOPER XL_capStepValue,
															  LPXLOPER XL_floorValue,
															  LPXLOPER XL_floorStepValue,
															  LPXLOPER XL_dualOptionFlag,
															  LPXLOPER XL_dualOptionStrike,
                                                              LPXLOPER XL_redempNoticeDate,
															  LPXLOPER XL_lastLiborFixing,
															  LPXLOPER XL_lastFxSpotFixing);
__declspec(dllexport) LPXLOPER WINAPI Local_PXL_ARM_POWERREVERSE (LPXLOPER XL_initPeriodLeg,
																  LPXLOPER XL_realFundLeg,
																  LPXLOPER XL_fxUnderLeg,
																  LPXLOPER XL_fxNumLeg,
																  LPXLOPER XL_noticeDates,
																  LPXLOPER XL_cancelDates,
																  LPXLOPER XL_FX0,
																  LPXLOPER XL_fxStep,
																  LPXLOPER XL_capValue,
																  LPXLOPER XL_capStepValue,
																  LPXLOPER XL_floorValue,
																  LPXLOPER XL_floorStepValue,
																  LPXLOPER XL_dualOptionFlag,
																  LPXLOPER XL_dualOptionStrike,
                                                                  LPXLOPER XL_redempNoticeDate,
																  LPXLOPER XL_lastLiborFixing,
																  LPXLOPER XL_lastFxSpotFixing);
__declspec(dllexport) LPXLOPER WINAPI Local_DataFromPowerReverse(
    LPXLOPER XL_prcsId,
    LPXLOPER XL_DataType );

__declspec(dllexport) LPXLOPER WINAPI Local_ARM_GETPRCSDATA (LPXLOPER XL_prcs);

__declspec(dllexport) LPXLOPER WINAPI Local_ARM_DELETENEXTCALLFROMPRCS (LPXLOPER XL_prcs,
																		LPXLOPER XL_asOf);

__declspec(dllexport) LPXLOPER WINAPI Local_ARM_GETOPTIONDATES (LPXLOPER XL_prcs,
																LPXLOPER XL_dateType);

__declspec(dllexport) LPXLOPER WINAPI Local_ARM_GETDUALOPTIONSTRIKE (LPXLOPER XL_prcs);

#endif // ARM_XL_REV_LOCAL_H