		/// ==> STRUCTURE AND PF (24 functions)
		{
				" Local_PFMODFIT",
                " RRRRRRRRRR",							// 9 parametres d'entree + 1 parametre de retour
                " PFMODFIT",
                " ModelName,PorfolioId,As of date,[CurveId],[VList],[FList],[NagAlgo],[Step],[Horizon]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibrates a model with a given portfolio", 
                " Model name", 
                " Portfolio id",
				" As of date",
				" Curve id",
                " Values list",
                " Flags list",
                " Use of a Nag algorithm or not (default: 1)",
				" Number of steps (default: 50)",
				" Horizon date (default: 31/12/2011)"
        },
		{
				" Local_PFMODFIT",
                " RRRRRRRRRR",							// 9 parametres d'entree + 1 parametre de retour
                " ARM_PFMODFIT",
                " ModelName,PorfolioId,As of date,[CurveId],[VList],[FList],[NagAlgo],[Step],[Horizon]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                IDH_ARM_PFMODFIT,
                " Calibrates a model with a given portfolio", 
                " Model name", 
                " Portfolio id",
				" As of date",
				" Curve id",
                " Values list",
                " Flags list",
                " Use of a Nag algorithm or not (default: 1)",
				" Number of steps (default: 50)",
				" Horizon date (default: 31/12/2011)"
        },
		{
				" Local_PXL_PFMODFIT",
                " RRRRRRRRRR",							// 9 parametres d'entree + 1 parametre de retour
                " PXL_PFMODFIT",
                " ModelName,PorfolioId,As of date,[CurveId],[VList],[FList],[NagAlgo],[Step],[Horizon]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibrates a model with a given portfolio", 
                " Model name", 
                " Portfolio id",
				" As of date",
				" Curve id",
                " Values list",
                " Flags list",
                " Use of a Nag algorithm or not (default: 1)",
				" Number of steps (default: 50)",
				" Horizon date (default: 31/12/2011)"
        },
		{
				" Local_PXL_PFMODFIT",
                " RRRRRRRRRR",							// 9 parametres d'entree + 1 parametre de retour
                " PXL_ARM_PFMODFIT",
                " ModelName,PorfolioId,As of date,[CurveId],[VList],[FList],[NagAlgo],[Step],[Horizon]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibrates a model with a given portfolio", 
                " Model name", 
                " Portfolio id",
				" As of date",
				" Curve id",
                " Values list",
                " Flags list",
                " Use of a Nag algorithm or not (default: 1)",
				" Number of steps (default: 50)",
				" Horizon date (default: 31/12/2011)"
        },
		{
				" Local_PF",
                " RRRRR",									// 4 parametres d'entree + 1 parametre de retour
                " PF",
                " InstrumentsId,Coefficients,MarketPrices,[Precisions]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Creates a portfolio", 
                " Instruments array", 
                " Weights array",
				" Market prices array",
				" Precisions array (default NULL)"
        },

        {
				" Local_PXL_PF",
                " RRRRR",									// 4 parametres d'entree + 1 parametre de retour
                " PXL_PF",
                " InstrumentsId,Coefficients,MarketPrices,[Precisions]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Creates a portfolio", 
                " Instruments array", 
                " Weights array",
				" Market prices array",
				" Precisions array (default NULL)"
        },

		{
				" Local_PF",
                " RRRRR",									// 4 parametres d'entree + 1 parametre de retour
                " ARM_PF",
                " InstrumentsId,Coefficients,MarketPrices,[Precisions]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                IDH_ARM_PF,
                " Creates a portfolio", 
                " Instruments array", 
                " Weights array",
				" Market prices array",
				" Precisions array (default NULL)"
        },
		
		{
				" Local_PXL_PF",
                " RRRRR",									// 4 parametres d'entree + 1 parametre de retour
                " PXL_ARM_PF",
                " InstrumentsId,Coefficients,MarketPrices,[Precisions]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Creates a portfolio", 
                " Instruments array", 
                " Weights array",
				" Market prices array",
				" Precisions array (default NULL)"
        },

        {
				" Local_PF_FILL",
                " RRRRRR",									// 5 parametres d'entree + 1 parametre de retour
                " ARM_PF_FILL",
                " AssetsId,Weights,MktPrices,Precisions,[PortfolioId]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                IDH_ARM_PF,
                " Creates a portfolio", 
                " Assets array", 
                " Weights array",
				" Market prices array",
				" Precisions array",
                " Portfolio Id (default NULL)"                
        },
		
		{
				" Local_PXL_PF_FILL",
                " RRRRRR",									// 5 parametres d'entree + 1 parametre de retour
                " PXL_ARM_PF_FILL",
                " InstrumentsId,Coefficients,MarketPrices,Precisions,[PortfolioId]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Creates a portfolio", 
                " Instruments array", 
                " Weights array",
				" Market prices array",
				" Precisions array ",
                " Portfolio Id (default NULL)" 
        },

        {
				" Local_PF_Merge",
                " RR",									// 1 parametres d'entree + 1 parametre de retour
                " ARM_PF_Merge",
                " PortfolioIds",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                IDH_ARM_PF,
                " Merges a portfolio", 
                " Portfolio Ids vector"                
        },
		
		{
				" Local_PXL_PF_Merge",
                " RR",									// 1 parametres d'entree + 1 parametre de retour
                " PXL_ARM_PF_Merge",
                " PortfolioIds",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Merges a portfolio", 
                " Portfolio Ids vector" 
        },

		{
				" Local_PFGYCSIGVARFIT",
                " RRRRRRRRRR",							// 9 parametres d'entree + 1 parametre de retour
                " PFGYCSIGVARFIT",
                " PortFolioId,CurveId,MatCurve,[MinMeanRev],[MaxMeanRev],[MinVol],[MaxVol],[PrecisionMeanRev],[PrecisionVol]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibrates a variable sigma Hull-White 1 factor model with a given a portfolio", 
                " Portfolio id", 
                " Curve id",
				" Maturities curve",
				" Minimum mean reversion (default: -0.01)",
                " Maximum mean reversion (default: 0.2)",
                " Minimum volatility (default: 0.01)",
                " Maximum volatility (default: 0.2)",
				" Mean reversion precision (default: 0.01)",
				" Volatility precision (default: 0.0001)"
        },
		{
				" Local_PFGYCSIGVARFIT",
                " RRRRRRRRRR",							// 9 parametres d'entree + 1 parametre de retour
                " ARM_PFGYCSIGVARFIT",
                " PortFolioId,CurveId,MatCurve,[MinMeanRev],[MaxMeanRev],[MinVol],[MaxVol],[PrecisionMeanRev],[PrecisionVol]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                IDH_ARM_PFGYCSIGVARFIT,
                " Calibrates a variable sigma Hull-White 1 factor model with a given portfolio", 
                " Portfolio id", 
                " Curve id",
				" Maturities curve",
				" Minimum mean reversion (default: -0.01)",
                " Maximum mean reversion (default: 0.2)",
                " Minimum volatility (default: 0.01)",
                " Maximum volatility (default: 0.2)",
				" Mean reversion precision (default: 0.01)",
				" Volatility precision (default: 0.0001)"
        },
		{
				" Local_PXL_PFGYCSIGVARFIT",
                " RRRRRRRRRR",							// 9 parametres d'entree + 1 parametre de retour
                " PXL_PFGYCSIGVARFIT",
                " PortFolioId,CurveId,MatCurve,[MinMeanRev],[MaxMeanRev],[MinVol],[MaxVol],[PrecisionMeanRev],[PrecisionVol]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibrates a variable sigma Hull-White 1 factor model with a given portfolio", 
                " Portfolio id", 
                " Curve id",
				" Maturities curve",
				" Minimum mean reversion (default: -0.01)",
                " Maximum mean reversion (default: 0.2)",
                " Minimum volatility (default: 0.01)",
                " Maximum volatility (default: 0.2)",
				" Mean reversion precision (default: 0.01)",
				" Volatility precision (default: 0.0001)"
        },
		{
				" Local_PXL_PFGYCSIGVARFIT",
                " RRRRRRRRRR",							// 9 parametres d'entree + 1 parametre de retour
                " PXL_ARM_PFGYCSIGVARFIT",
                " PortFolioId,CurveId,MatCurve,[MinMeanRev],[MaxMeanRev],[MinVol],[MaxVol],[PrecisionMeanRev],[PrecisionVol]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibrates a variable sigma Hull-White 1 factor model with a given portfolio", 
                " Portfolio id", 
                " Curve id",
				" Maturities curve",
				" Minimum mean reversion (default: -0.01)",
                " Maximum mean reversion (default: 0.2)",
                " Minimum volatility (default: 0.01)",
                " Maximum volatility (default: 0.2)",
				" Mean reversion precision (default: 0.01)",
				" Volatility precision (default: 0.0001)"
        },
        {
				" Local_PFLOGDECVOLFIT",
                " RRRRRRRRRRRR",							// 11 parametres d'entree + 1 parametre de retour
                " PFLOGDECVOLFIT",
                " PortFolioId,CurveId,Probabilities,[Accuracy],[ShapeType],[Decay],[Slope],[Asymptote],[MatCurve],[VolInit],[Coeff]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibration of a Shifted LN Model with a Portfolio and given Probabilities", 
                " Portfolio id", 
                " Curve id",
				" Probas. vector LOG vs NORMAL",
				" Accuracy (default: 1E-12)",
				" ShapeType (default: 0 -in Row)",
				" Decay (default: 0.0)",
				" Slope (default: 0.0)",
				" Asymptote (default: 0.0)",
                " Maturities curve(dates) of the model (default: merged portfolio assets reset dates)",
                " Initial Volatilities",
                " Penalty Weights (default: 0.0)"
        },
        {
				" Local_PFLOGDECVOLFIT",
                " RRRRRRRRRRRR",							// 11 parametres d'entree + 1 parametre de retour
                " ARM_PFLOGDECVOLFIT",
                " PortFolioId,CurveId,Probabilities,[Accuracy],[ShapeType],[Decay],[Slope],[Asymptote],[MatCurve],[VolInit],[Coeff]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                IDH_ARM_PFLOGDECVOLFIT,
                " Calibration of a Shifted LN Model with a Portfolio and given Probabilities", 
                " Portfolio id", 
                " Curve id",
				" Probas. vector LOG vs NORMAL",
				" Accuracy (default: 1E-12)",
				" ShapeType (default: 0 -in Row)",
				" Decay (default: 0.0)",
				" Slope (default: 0.0)",
				" Asymptote (default: 0.0)",
                " Maturities curve(dates) of the model (default: merged portfolio assets reset dates)",
                " Initial Volatilities",
                " Penalty Weights (default: 0.0)"
        },
        {
				" Local_PXL_PFLOGDECVOLFIT",
                " RRRRRRRRRRRR",							// 11 parametres d'entree + 1 parametre de retour
                " PXL_PFLOGDECVOLFIT",
                " PortFolioId,CurveId,Probabilities,[Accuracy],[ShapeType],[Decay],[Slope],[Asymptote],[MatCurve],[VolInit],[Coeff]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibration of a Shifted LN Model with a Portfolio and given Probabilities", 
                " Portfolio id", 
                " Curve id",
				" Probas. vector LOG vs NORMAL",
				" Accuracy (default: 1E-12)",
				" ShapeType (default: 0 -in Row)",
				" Decay (default: 0.0)",
				" Slope (default: 0.0)",
				" Asymptote (default: 0.0)",
                " Maturities curve(dates) of the model (default: merged portfolio assets reset dates)",
                " Initial Volatilities",
                " Penalty Weights (default: 0.0)"
        },
        {
				" Local_PXL_PFLOGDECVOLFIT",
                " RRRRRRRRRRRR",							// 11 parametres d'entree + 1 parametre de retour
                " PXL_ARM_PFLOGDECVOLFIT",
                " PortFolioId,CurveId,Probabilities,[Accuracy],[ShapeType],[Decay],[Slope],[Asymptote],[MatCurve],[VolInit],[Coeff]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibration of a Shifted LN Model with a Portfolio and given Probabilities", 
                " Portfolio id", 
                " Curve id",
				" Probas. vector LOG vs NORMAL",
				" Accuracy (default: 1E-12)",
				" ShapeType (default: 0 -in Row)",
				" Decay (default: 0.0)",
				" Slope (default: 0.0)",
				" Asymptote (default: 0.0)",
                " Maturities curve(dates) of the model (default: merged portfolio assets reset dates)",
                " Initial Volatilities",
                " Penalty Weights (default: 0.0)"
        },
		{
				" Local_PFGYCSIGVARPENALFIT",
                " RRRRRRRRR",								// 8 parametres d'entree + 1 parametre de retour
                " PFGYCSIGVARPENALFIT",
                " PortFolioId,CurveId,MatCurve,[StartMeanRev],[StartVol],[PenalVect],[WeightVect],[Accuracy]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibrates a variable sigma Hull-White 1 factor model with a given portfolio with penalties method", 
                " Portfolio id", 
                " Curve id",
				" Maturities curve",
				" Mean reversion (default: 0.1)",
                " Volatility (default: 1.0)",
                " Penalties vector (default: 0.1)",
                " Weights vector (default: 0.0)",
				" Accuracy (default: 0.1)"
        },
		{
				" Local_PFGYCSIGVARPENALFIT",
                " RRRRRRRRR",								// 8 parametres d'entree + 1 parametre de retour
                " ARM_PFGYCSIGVARPENALFIT",
                " PortFolioId,CurveId,MatCurve,[StartMeanRev],[StartVol],[PenalVect],[WeightVect],[Accuracy]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                IDH_ARM_PFGYCSIGVARPENALFIT,
                " Calibrates a variable sigma Hull-White 1 factor model with a given portfolio with penalties method", 
                " Portfolio id", 
                " Curve id",
				" Maturities curve",
				" Mean reversion (default: 0.1)",
                " Volatility (default: 1.0)",
                " Penalties vector (default: 0.1)",
                " Weights vector (default: 0.0)",
				" Accuracy (default: 0.1)"
        },
		{
				" Local_PXL_PFGYCSIGVARPENALFIT",
                " RRRRRRRRR",								// 8 parametres d'entree + 1 parametre de retour
                " PXL_PFGYCSIGVARPENALFIT",
                " PortFolioId,CurveId,MatCurve,[StartMeanRev],[StartVol],[PenalVect],[WeightVect],[Accuracy]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibrates a variable sigma Hull-White 1 factor model with a given portfolio with penalties method", 
                " Portfolio id", 
                " Curve id",
				" Maturities curve",
				" Mean reversion (default: 0.1)",
                " Volatility (default: 1.0)",
                " Penalties vector (default: 0.1)",
                " Weights vector (default: 0.0)",
				" Accuracy (default: 0.1)"
        },
		{
				" Local_PXL_PFGYCSIGVARPENALFIT",
                " RRRRRRRRR",								// 8 parametres d'entree + 1 parametre de retour
                " PXL_ARM_PFGYCSIGVARPENALFIT",
                " PortFolioId,CurveId,MatCurve,[StartMeanRev],[StartVol],[PenalVect],[WeightVect],[Accuracy]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibrates a variable sigma Hull-White 1 factor model with a given portfolio with penalties method", 
                " Portfolio id", 
                " Curve id",
				" Maturities curve",
				" Mean reversion (default: 0.1)",
                " Volatility (default: 1.0)",
                " Penalties vector (default: 0.1)",
                " Weights vector (default: 0.0)",
				" Accuracy (default: 0.1)"
        },
        {
				" Local_PFINSTLOGDECVOLFIT",
                " RRRRRRRRRRRRRRR",				// 14 parametres d'entree + 1 parametre de retour
                " PFINSTLOGDECVOLFIT",
                " PortfolioId,SecurityId,CurveId,Probabilities,[UsePFResetDates],[Accuracy],[ShapeType],[Decay],[Slope],[Asymptote],[VolBSInit],[MatCurve],[VolInit],[Coeff]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibration of a Shifted LN Model with a Portfolio and given Probabilities, using the Instrument Reset Dates", 
                " Portfolio id",
				" Security id", 
                " Curve id",
				" Probas. vector LOG vs NORMAL",
				" UsePFResetDates (default 0)",
				" Accuracy (default: 1E-12)",
				" ShapeType (default: 0 -in Row)",
				" Decay (default: 0.0)",
				" Slope (default: 0.0)",
				" Asymptote (default: 0.0)",
				" Vol Black Initiale (calage sur matrice ATM)",
                " Maturities curve(dates) of the model (default: merged portfolio assets reset dates)",
                " Initial Volatilities",
                " Penalty Weights (default: 0.0)"
        },
        {
				" Local_PFINSTLOGDECVOLFIT",
                " RRRRRRRRRRRRRRR",				// 14 parametres d'entree + 1 parametre de retour
                " ARM_PFINSTLOGDECVOLFIT",
                " PortfolioId,SecurityId,CurveId,Probabilities,[UsePFResetDates],[Accuracy],[ShapeType],[Decay],[Slope],[Asymptote],[VolBSInit],[MatCurve],[VolInit],[Coeff]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                IDH_ARM_PFINSTLOGDECVOLFIT,
                " Calibration of a Shifted LN Model with a Portfolio and given Probabilities, using the Instrument Reset Dates", 
                " Portfolio id",
				" Security id", 
                " Curve id",
				" Probas. vector LOG vs NORMAL",
				" UsePFResetDates (default 0)",
				" Accuracy (default: 1E-12)",
				" ShapeType (default: 0 -in Row)",
				" Decay (default: 0.0)",
				" Slope (default: 0.0)",
				" Asymptote (default: 0.0)",
				" Vol Black Initiale (calage sur matrice ATM)",
                " Maturities curve(dates) of the model (default: merged portfolio assets reset dates)",
                " Initial Volatilities",
                " Penalty Weights (default: 0.0)"
        },
        {
				" Local_PXL_PFINSTLOGDECVOLFIT",
                " RRRRRRRRRRRRRRR",				// 14 parametres d'entree + 1 parametre de retour
                " PXL_PFINSTLOGDECVOLFIT",
                " PortfolioId,SecurityId,CurveId,Probabilities,[UsePFResetDates],[Accuracy],[ShapeType],[Decay],[Slope],[Asymptote],[VolBSInit],[MatCurve],[VolInit],[Coeff]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibration of a Shifted LN Model with a Portfolio and given Probabilities, using the Instrument Reset Dates", 
                " Portfolio id",
				" Security id", 
                " Curve id",
				" Probas. vector LOG vs NORMAL",
				" UsePFResetDates (default 0)",
				" Accuracy (default: 1E-12)",
				" ShapeType (default: 0 -in Row)",
				" Decay (default: 0.0)",
				" Slope (default: 0.0)",
				" Asymptote (default: 0.0)",
				" Vol Black Initiale (calage sur matrice ATM)",
                " Maturities curve(dates) of the model (default: merged portfolio assets reset dates)",
                " Initial Volatilities",
                " Penalty Weights (default: 0.0)"
        },
        {
				" Local_PXL_PFINSTLOGDECVOLFIT",
                " RRRRRRRRRRRRRRR",				// 14 parametres d'entree + 1 parametre de retour
                " PXL_ARM_PFINSTLOGDECVOLFIT",
                " PortfolioId,SecurityId,CurveId,Probabilities,[UsePFResetDates],[Accuracy],[ShapeType],[Decay],[Slope],[Asymptote],[VolBSInit],[MatCurve],[VolInit],[Coeff]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Calibration of a Shifted LN Model with a Portfolio and given Probabilities, using the Instrument Reset Dates", 
                " Portfolio id",
				" Security id", 
                " Curve id",
				" Probas. vector LOG vs NORMAL",
				" UsePFResetDates (default 0)",
				" Accuracy (default: 1E-12)",
				" ShapeType (default: 0 -in Row)",
				" Decay (default: 0.0)",
				" Slope (default: 0.0)",
				" Asymptote (default: 0.0)",
				" Vol Black Initiale (calage sur matrice ATM)",
                " Maturities curve(dates) of the model (default: merged portfolio assets reset dates)",
                " Initial Volatilities",
                " Penalty Weights (default: 0.0)"
        },
		{
				" Local_ARM_CalibrationPF",
                " RRRRRRR",					// 6 parametres d'entree + 1 parametre de retour
                " ARM_CalibrationPF",
                " ZcId,VolId,secId,[modeType],[PortfolioType], [Shift]",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Creates a portfolio adapted to the security to calibrate the pricing model",
                " zc id",
				" vol curve id",
				" security id",
				" modeType default mode SUMMIT else MANUAL",
				" PortfolioType 0 (Volatility), 1 (Shift), 2 (MRS)",
				" Strike Shift for Shift Calib Portfolio (default = - 0.5)"              
        },
		{
				" Local_PXL_ARM_CalibrationPF",
                " RRRRRRR",					// 6 parametres d'entree + 1 parametre de retour
                " PXL_ARM_CalibrationPF",
                " ZcId,VolId,secId,[modeType],[PortfolioType], [Shift]",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
				" ",
                " Creates a portfolio adapted to the security to calibrate the pricing model",
                " zc id",
				" vol curve id",
				" security id",
				" modeType default mode SUMMIT else MANUAL",
				" PortfolioType 0 (Volatility), 1 (Shift), 2 (MRS)",
				" Strike Shift for Shift Calib Portfolio (default = - 0.5)"
        },
		{
				" Local_ARM_MRSCalibrationPF",
                " RRRRRRR",					// 6 parametres d'entree + 1 parametre de retour
                " ARM_MRSCalibrationPF",
                " ZcId,BsModelId,secId,portfolioId,freq, atmFlag",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Creates a portfolio adapted to the security to calibrate the pricing model",
                " zc id",
				" BsModel id",
				" security id",
				" portfolio id",
				" Freq (0,2,4)",
				" ARM Flag (same strikes else) "              
        },
		{
				" Local_PXL_ARM_MRSCalibrationPF",
                " RRRRRRR",					// 6 parametres d'entree + 1 parametre de retour
                " PXL_ARM_MRSCalibrationPF",
                " ZcId,VolId,secId,portfolioId,freq, atmFlag",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
				" ",
                " Creates a portfolio adapted to the security to calibrate the pricing model",
                " zc id",
				" vol curve id",
				" security id",
				" portfolio id",
				" Freq (0,2,4)",
				" ARM Flag (same strikes else) "      
        },

        {
				" Local_GetAssetFromPF",
                " RRR",					// 2 parametres d'entree + 1 parametre de retour
                " ARM_GetAssetFromPF",
                " PortfolioId,AssetIdIdex",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Get an Asset referenced with index from a portfolio ",
                " portfolio id",
				" asset id index"               
        },
        {
				" Local_PXL_GetAssetFromPF",
                " RRR",					// 2 parametres d'entree + 1 parametre de retour
                " PXL_ARM_GetAssetFromPF",
                " PortfolioId,AssetIdIdex",
                " 0",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Get an Asset referenced with index from a portfolio ",
                " portfolio id",
				" asset id index"               
        },

        {
				" Local_GetSizeOfPF",
                " RR",					// 1 parametres d'entree + 1 parametre de retour
                " ARM_GetSizeOfPF",
                " PortfolioId",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Get size of portfolio ",
                " portfolio id"
                
        },
        {
				" Local_ComputeAll",
                " RRR",					// 2 parametres d'entree + 1 parametre de retour
                " ARM_ComputeAll",
                " PortfolioId, ModelId",
                " 1",
                XLLOCALARM_STRUCT_GROUP,
                " ",
                " ",
                " Compute all the portfolio ",
                " portfolio id",
				" model id"
        },
