// This file is automatically generated from TreeLib.cpp (which see for more info)
// Do not edit it: your changes will be overwritten.
// Do not add it to the Subversion repository.















#include "edginc/config.hpp"
#include "edginc/TreeLib.hpp"
#include "edginc/ModelException.hpp"




#include "edginc/ToolkitDebug.hpp"






DRLIB_BEGIN_NAMESPACE


extern bool RateTreeLoad();
extern bool CreditTreeLoad();
extern bool Fix3Load();
extern bool Fix3CBLoad();
extern bool Hyb3Load();
extern bool Hyb3CBLoad();
extern bool Hyb3EQLoad();
extern bool Hyb3CBEQLoad();
extern bool Hyb3CBFXLoad();
extern bool SMDLoad();
extern bool Fix32QLoad();
extern bool Fix3TDLoad();
extern bool TMXLoad();
extern bool RatesUtilsLoad();
extern bool QuasiMQLoad();

void CTreeLib::linkInClasses(){
    /* The sole purpose of this method is to ensure that the linker 
       includes all symbols out of the market directory. Many symbols
       are automatically linked because they are used by other classes
       which are already included. */

    /* there is no order dependency - this could be automated */

    // Please don't add any new ...::TYPE entries here ---

    bool success =


        RatesUtilsLoad()         &&

        RateTreeLoad()           &&
        Fix3Load()               &&
        Fix3CBLoad()             &&
        Hyb3Load()               &&
        Hyb3CBLoad()             &&
        Hyb3EQLoad()             &&
        Hyb3CBEQLoad()           &&
        Hyb3CBFXLoad()           &&
        SMDLoad()                &&
        Fix3TDLoad()             &&
        Fix32QLoad()             &&
        TMXLoad()                &&
        CreditTreeLoad()         &&
        
        QuasiMQLoad()            &&


        
        true;
           
    if (!success){
        throw ModelException("CTreeLib::registerClasses",
                             "Registration error");
    }

}
DRLIB_END_NAMESPACE