// This file is automatically generated from c:/rates/qlib/trunk/code/drlib/irproducts/src/IRProductsLib.cpp (which see for more info)
// Do not edit it: your changes will be overwritten.
// Do not add it to the Subversion repository.





























#include "edginc/config.hpp"
#include "edginc/IRProductsLib.hpp"
#include "edginc/ModelException.hpp"
#include "edginc/ToolkitDebug.hpp"

DRLIB_BEGIN_NAMESPACE
extern bool CallableTurboLoad();
extern bool CallableTurbo2Load();
extern bool TurboSwapLoad();
extern bool KOptionLoad();
extern bool KComponentLoad();
extern bool KRibLoad();
extern bool CallableRibLoad();
extern bool KSumLoad();
extern bool KTurboLoad();
extern bool KKnockOutLoad();
extern bool KFloatLegLoad();
extern bool KRibFloatLegLoad();
extern bool CouponSchedLoad();
extern bool OptionSchedLoad();
extern bool KRiskyComponentLoad();
extern bool KTarnLoad();
extern bool KKOSwapLoad();
extern bool CallableKOSwapLoad();
extern bool KAccumulatedCFLoad();
extern bool KKOOptionLoad();
extern bool KRibTurboLoad();
extern bool KCashflowLoad();
extern bool OptionGridLoad();
extern bool KForwardOptionLoad();
extern bool QuasiVanillaLoad();
extern bool SimpleRibLoad();
extern bool VnfmTestLoad();
extern bool VnfmTestTimeLoad();
extern bool VolToolsLoad();
extern bool SharedEnumsLoad();
extern bool KBarrierLoad();
extern bool KKnockIOLoad();
extern bool KBoolExprLoad();

void IRProductsLib::linkInClasses(){
    /* The sole purpose of this method is to ensure that the linker 
       includes all symbols out of the market directory. Many symbols
       are automatically linked because they are used by other classes
       which are already included.

       An example of symbols that could be dropped would be an entire class
       representing a product. For example Vanilla might be dropped since
       the only references might be throught the abstract parent class. */


    /* there is no order dependency - this could be automated */

    // Please don't add any new ...::TYPE entries here ---

    bool success =
        SharedEnumsLoad() &&
        CallableTurboLoad() &&
        CallableTurbo2Load() &&
        TurboSwapLoad() &&
        KOptionLoad() &&
        KComponentLoad() &&
        KRibLoad() &&
        CallableRibLoad() &&
        KSumLoad() &&
        KTurboLoad() &&
        KKnockOutLoad() &&
        KFloatLegLoad() &&
        KRibFloatLegLoad() &&
        CouponSchedLoad() &&
        OptionSchedLoad() &&
        KTarnLoad()       &&
        KKOSwapLoad()     &&
        CallableKOSwapLoad() &&
        KAccumulatedCFLoad() &&
        KKOOptionLoad() &&
        KRibTurboLoad() &&
        KCashflowLoad() &&
        OptionGridLoad()  &&
        KForwardOptionLoad()  &&
        SimpleRibLoad() &&
		QuasiVanillaLoad() &&
		VnfmTestLoad() &&
		VnfmTestTimeLoad() &&
		VolToolsLoad() &&
		KBarrierLoad() &&
		KKnockIOLoad() &&
		KBoolExprLoad() &&
        true;

    if (!success){
        throw ModelException("IRProductsLib::registerClasses",
                             "Registration error");
    }
}

DRLIB_END_NAMESPACE