#include "../credit/src/pch-credit.cxx"

/*
#include "../irproducts/edginc/CouponSched.hpp"
#include "../irproducts/edginc/FlexDates.hpp"
#include "../irproducts/edginc/IRProductsLib.hpp"
#include "../irproducts/edginc/KAccumulatedCF.hpp"
#include "../irproducts/edginc/KCashflow.hpp"
#include "../irproducts/edginc/KComplexOption.hpp"
#include "../irproducts/edginc/KComponent.hpp"
#include "../irproducts/edginc/KFloatLeg.hpp"
#include "../irproducts/edginc/KKnockOut.hpp"
#include "../irproducts/edginc/KKOOption.hpp"
#include "../irproducts/edginc/KKOSwap.hpp"
#include "../irproducts/edginc/KOption.hpp"
#include "../irproducts/edginc/KProtectionLeg.hpp"
#include "../irproducts/edginc/KRib.hpp"
#include "../irproducts/edginc/KRib2.hpp"
#include "../irproducts/edginc/KRibFloatLeg.hpp"
#include "../irproducts/edginc/KRibTurbo.hpp"
#include "../irproducts/edginc/KRiskyComponent.hpp"
#include "../irproducts/edginc/KSum.hpp"
#include "../irproducts/edginc/KTarn.hpp"
#include "../irproducts/edginc/KTurbo.hpp"
#include "../irproducts/edginc/OptionSched.hpp"
#include "../irproducts/edginc/QuasiVanilla.hpp"
#include "../irproducts/edginc/QuasiVanillaModel.hpp"
#include "../irproducts/edginc/SharedEnums.hpp"
*/
