/* -----------------------------------------------------------------
   -----------------------------------------------------------------

	FILE:		ENUMS.H
	PROJECT:	KERNEL
	
	DESCRIPTION:	list of enumerated types

   -----------------------------------------------------------------
   
	CAIR Library

		version 1.0
		developped by Laurent Jacquel

  -----------------------------------------------------------------
  ----------------------------------------------------------------- */


# ifndef _ENUMS
# define _ENUMS

enum	BumpType{BT_ADD, BT_MULT};

enum	CreditHedgeBump{CHB_NO, CHB_SPREAD_ALL_MATURITIES, CHB_SPREAD_PARALLEL, CHB_FAST_SPREAD_PARALLEL, CHB_DEFAULT, CHB_RECOVERY_SENS, CHB_RECOVERY_LOSS, CHB_RECOVERY_GLOBAL, CHB_CORRELATION};

enum	TimeUnit{TU_DAY, TU_BUSINESSDAY, TU_WEEK, TU_MONTH, TU_YEAR};

enum	CurrencyName{EUR};

enum	CreditCategory{CC_AUTO, CC_BANK, CC_CONSUMER, CC_UTILITIES};

enum	CorrelationType{CT_FLAT, CT_BETA, CT_MATRIX, CT_FACTOR_LOADING_2, CT_BASE_STRIKE, CT_SECTORIAL};

enum	CreditModelType{CMT_MONTECARLO, CMT_ANALYTIC_RECURSIVE_1F, CMT_ANALYTIC_RECURSIVE_INTERPOLATION_1F, CMT_ANALYTIC_LARGE_PORTFOLIO_1F, CMT_ANALYTIC_LHP, CMT_ANALYTIC_LHP_JPM, CMT_ANALYTIC_LHP_PLUS, CMT_ANALYTIC_RECURSIVE_STOCHASTIC_CORRELATION_BERNOULLI_1F, CMT_ANALYTIC_FFT_1F};

enum	CreditCopulaType{CCT_GAUSSIAN, CCT_STUDENT, CCT_NIG};

enum	CreditBasketNPV{CBN_DEFAULTMINUSPREMIUM, CBN_PREMIUMMINUSDEFAULT, CBN_PREMIUMLEGONLY, CBN_DEFAULTLEGONLY};

enum	CreditEventPayment{CEP_ATDEFAULTDATE, CEP_ATNEXTCREDITDATE, CEP_ATNEXTPAYMENTDATE, CEP_ATFIXEDDATE};

enum	CreditObservation{CO_NBDEFAULTS, CO_LOSSES};
enum	CreditAccruedPayment{CAP_PRORATA, CAP_NON_PRORATA};

enum	CreditPremiumLegATMData{CPLADT_PURESPREAD, CPLADT_UF_UPFRONT, CPLADT_UF_SPREAD};
enum	CreditNPV{CNPV_STANDARD, CNPV_WITH_RUNNING_SPREAD, CNPV_WITH_UP_FRONT_PREMIUM, CNPV_WITH_RUNNING_SPREAD_AND_UP_FRONT_PREMIUM};

enum	CreditPremiumLegType{CPLT_GUARANTEED, CPLT_NOTIONAL, CPLT_OUTSTANDING, /* CPLT_CUMULCOUPON, */CPLT_CUMULREDEMPTION};

enum	CreditCalibratorSelection{CCS_SINGLENAME, CCS_NTD, CCS_NLOSS, CCS_DENSITY_NTD, CCS_DENSITY_LOSS, CCS_EXPECTED_LOSS};

enum	CreditLossComputation{CLC_PROBABILITY, CLC_EXPECTATION, CLC_PROBABILITY_INTERPOLATION, CLC_EXPECTATION_INTERPOLATION, CLC_EXPECTATION_DERIV_SPREAD};

enum	CreditMonteCarloVarianceReduction{CMCVR_NONE, CMCVR_IS_IDIOSYNCRATIC, CMCVR_IS_PURE_FACTORS, CMCVR_IS_FACTORS};

enum	CreditOneFactorRecursiveLossUnitChoice{COFRLUC_PGCD, COFRLUC_LOSS_UNIT_MIN, COFRLUC_NB_LOSS_STEP};

enum	CreditVarianceReductionIdiosyncratic{CVRI_IMPOSED, CVRI_OPTIM};
enum	CreditVarianceReductionFactors{CVRF_IMPOSED, CVRF_TARGET_DEFPROB, CVRF_OPTIM};

enum	CreditProductType{CPT_STD_CDO, CPT_CDO_SQUARE};

// mix of Numerical Method and of Copula Choice
enum	CreditManager_Model{CMM_LHP_GAUSSIAN, CMM_LHP_JPM_GAUSSIAN, CMM_LHP_JPM_NIG, CMM_HT_JPM_GAUSSIAN, CMM_RSCB, CMM_ANDERSEN_GAUSSIAN};

enum	CreditManager_Correlation_Calibration{CMCC_FROM_LHP_COMPOUND_TO_LHP_BASE, CMCC_FROM_LHP_JPM_COMPOUND_TO_LHP_JPM_BASE, CMCC_FROM_HT_JPM_COMPOUND_TO_HT_JPM_BASE, CMCC_FROM_LHP_JPM_COMPOUND_TO_LHP_JPM_NIG};
enum	CreditManager_Correlation_Calibration_Input{CMCCI_COMPOUND_CORRELATION, CMCCI_SPREADS, CMCCI_BASE_CORRELATION};

enum	CreditManager_Correlation_Type{CMCT_COMPOUND_CORRELATION, CMCT_BASE_CORRELATION, CMCT_NIG_CORRELATION};


enum	Correlation_RFL{CRFL_2F_CONSTANT, CRFL_2F_INDIVIDUAL, CRFL_TANH};

# endif

