// This file is automatically generated from MonteCarloLib.cpp (which see for more info)
// Do not edit it: your changes will be overwritten.
// Do not add it to the Subversion repository.














#include "edginc/config.hpp"
#include "edginc/MonteCarloLib.hpp"
#include "edginc/ModelException.hpp"
#include "edginc/MonteCarlo.hpp" // FILTER
#include "edginc/MCPathConfig.hpp" // FILTER
#include "edginc/HitSample.hpp" // FILTER

DRLIB_BEGIN_NAMESPACE
extern bool MCPathConfigLNLoad();      // avoid need for header file
extern bool MCPathConfigImpliedLoad(); // avoid need for header file
extern bool MonteCarloTurboLoad();
extern bool MCPathConfigLVLoad();
extern bool MCPathConfigMertonLoad();
extern bool MertonDependenceLoad();
extern bool MCPathConfigLVMertonLoad();
extern bool MCPathConfigSVLoad();
extern bool MCPathConfigSVJLoad();
extern bool MCPathConfigSVCJLoad();
extern bool MCPathConfigDemoLoad();
extern bool MCPathConfigSRMLoad();
extern bool MCPathConfigCCMLoad();
extern bool MCPathConfigE3FLoad();
extern bool SimpathILoad();
extern bool AdaptiveSamplingLoad();
extern bool IMFSamplingLoad();
extern bool ArbSamplingLoad();
extern bool GaussSamplingLoad();
extern bool ConditionalLossModelLoad();
extern bool ITimelineSpecload();

void MonteCarloLib::linkInClasses(){

    // Please don't add any new ...::TYPE entries here ---

    bool success =
         MonteCarlo::TYPE != 0 &&
         MCPathConfig::TYPE != 0 &&
         MonteCarloTurboLoad() &&
         MCPathConfigLNLoad() &&
         MCPathConfigImpliedLoad() &&
        MCPathConfigLVLoad() &&
        MCPathConfigMertonLoad() &&
        MertonDependenceLoad() &&
        MCPathConfigLVMertonLoad() &&
        MCPathConfigSVLoad() &&
        MCPathConfigSVJLoad() &&
        MCPathConfigSVCJLoad() &&
        MCPathConfigDemoLoad() &&
		MCPathConfigE3FLoad() &&
		MCPathConfigCCMLoad() &&
        HitSample::TYPE != 0 &&
        MCPathConfigSRMLoad() &&
        SimpathILoad() &&
		SimpathILoad() &&
		AdaptiveSamplingLoad() &&
		GaussSamplingLoad() &&
		IMFSamplingLoad() &&
		ArbSamplingLoad() &&
		ConditionalLossModelLoad() &&
		ITimelineSpecload() &&
        true;

    if (!success){
        throw ModelException("MonteCarloLib::registerClasses",
                             "Registration error");
    }
}

DRLIB_END_NAMESPACE