#ifndef ARM_XL_SWAP_LOCAL_H
#define ARM_XL_SWAP_LOCAL_H



//#include "XL_local_api.h"



__declspec(dllexport) LPXLOPER WINAPI Local_LiborAssetSwapMargin (LPXLOPER XL_model,
																  LPXLOPER XL_startDate,
																  LPXLOPER XL_endDate,
																  LPXLOPER XL_fixedRate,
																  LPXLOPER XL_fixDayCount,
																  LPXLOPER XL_fixFrequency,
																  LPXLOPER XL_fixDecompFrequency,
																  LPXLOPER XL_fixPayTiming,
																  LPXLOPER XL_fixIntRule,
																  LPXLOPER XL_liborType,
																  LPXLOPER XL_floatResetFreq,
																  LPXLOPER XL_floatPayFreq,
																  LPXLOPER XL_price,
																  LPXLOPER XL_discountCcy,
																  LPXLOPER XL_redemptionPrice,
																  LPXLOPER XL_supplFee);

__declspec(dllexport) LPXLOPER WINAPI Local_LIBORSWAP (LPXLOPER XL_startDate,
													   LPXLOPER XL_endDate,
													   LPXLOPER XL_liborType,
													   LPXLOPER XL_receiveOrPay,
													   LPXLOPER XL_fixedRate,
													   LPXLOPER XL_spread,
													   LPXLOPER XL_ccy,
													   LPXLOPER XL_fixedDayCount,
													   LPXLOPER XL_floatingDayCount);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_LIBORSWAP (LPXLOPER XL_startDate,
														   LPXLOPER XL_endDate,
														   LPXLOPER XL_liborType,
														   LPXLOPER XL_receiveOrPay,
														   LPXLOPER XL_fixedRate,
														   LPXLOPER XL_spread,
														   LPXLOPER XL_ccy,
														   LPXLOPER XL_fixedDayCount,
														   LPXLOPER XL_floatingDayCount);

__declspec(dllexport) LPXLOPER WINAPI Local_LIBORLEG (LPXLOPER XL_startDate,
													  LPXLOPER XL_endDate,
													  LPXLOPER XL_liborType,
													  LPXLOPER XL_receiveOrPay,
													  LPXLOPER XL_spread,
													  LPXLOPER XL_resetFreq,
													  LPXLOPER XL_payFreq,
													  LPXLOPER XL_resetTiming,
													  LPXLOPER XL_payTiming,
													  LPXLOPER XL_ccy,
													  LPXLOPER XL_intRule,
													  LPXLOPER XL_resetGap,
													  LPXLOPER XL_resetCal,
													  LPXLOPER XL_payCal,
													  LPXLOPER XL_decompPricingFlag,
													  LPXLOPER XL_nxChange,
													  LPXLOPER XL_stubRule,
													  LPXLOPER XL_refDate,
													  LPXLOPER XL_adjStartDate,
													  LPXLOPER XL_couponDayCount);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_LIBORLEG (LPXLOPER XL_startDate,
														  LPXLOPER XL_endDate,
														  LPXLOPER XL_liborType,
														  LPXLOPER XL_receiveOrPay,
														  LPXLOPER XL_spread,
														  LPXLOPER XL_resetFreq,
														  LPXLOPER XL_payFreq,
														  LPXLOPER XL_resetTiming,
														  LPXLOPER XL_payTiming,
														  LPXLOPER XL_ccy,
														  LPXLOPER XL_intRule,
														  LPXLOPER XL_resetGap,
														  LPXLOPER XL_resetCal,
														  LPXLOPER XL_payCal,
														  LPXLOPER XL_decompPricingFlag,
														  LPXLOPER XL_nxChange,
														  LPXLOPER XL_stubRule,
														  LPXLOPER XL_refDate,
														  LPXLOPER XL_adjStartDate,
														  LPXLOPER XL_couponDayCount);

__declspec(dllexport) LPXLOPER WINAPI Local_SWAPLEG (LPXLOPER XL_irIndex,
													 LPXLOPER XL_startDate,
													 LPXLOPER XL_endDate,
													 LPXLOPER XL_receiveOrPay,
													 LPXLOPER XL_spread,
													 LPXLOPER XL_ccy,
													 LPXLOPER XL_dayCount,
													 LPXLOPER XL_resetGap,
													 LPXLOPER XL_resetCal,
													 LPXLOPER XL_payCal,
													 LPXLOPER XL_decompPricingFlag,
													 LPXLOPER XL_nxChange,
													 LPXLOPER XL_stubRule,
													 LPXLOPER XL_refDate,
													 LPXLOPER XL_adjStartDate,
													 LPXLOPER XL_rollDay);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_SWAPLEG (LPXLOPER XL_irIndex,
														 LPXLOPER XL_startDate,
														 LPXLOPER XL_endDate,
														 LPXLOPER XL_receiveOrPay,
														 LPXLOPER XL_spread,
														 LPXLOPER XL_ccy,
														 LPXLOPER XL_dayCount,
														 LPXLOPER XL_resetGap,
														 LPXLOPER XL_resetCal,
														 LPXLOPER XL_payCal,
														 LPXLOPER XL_decompPricingFlag,
														 LPXLOPER XL_nxChange,
														 LPXLOPER XL_stubRule,
														 LPXLOPER XL_refDate,
														 LPXLOPER XL_adjStartDate,
														 LPXLOPER XL_rollDay);

__declspec(dllexport) LPXLOPER WINAPI Local_FIXEDLEG (LPXLOPER XL_startDate,
													  LPXLOPER XL_endDate,
													  LPXLOPER XL_receiveOrPay,
													  LPXLOPER XL_fixRate,
													  LPXLOPER XL_dayCount,
													  LPXLOPER XL_freq,
													  LPXLOPER XL_decompFreq,
													  LPXLOPER XL_payTiming,
													  LPXLOPER XL_intRule,
													  LPXLOPER XL_stubRule,
													  LPXLOPER XL_ccy,
													  LPXLOPER XL_payCal,
													  LPXLOPER XL_nxChange,
													  LPXLOPER XL_refDate,
													  LPXLOPER XL_adjStartDate,
													  LPXLOPER XL_rollDay);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_FIXEDLEG (LPXLOPER XL_startDate,
														  LPXLOPER XL_endDate,
														  LPXLOPER XL_receiveOrPay,
														  LPXLOPER XL_fixRate,
														  LPXLOPER XL_dayCount,
														  LPXLOPER XL_freq,
														  LPXLOPER XL_decompFreq,
														  LPXLOPER XL_payTiming,
														  LPXLOPER XL_intRule,
														  LPXLOPER XL_stubRule,
														  LPXLOPER XL_ccy,
														  LPXLOPER XL_payCal,
														  LPXLOPER XL_nxChange,
														  LPXLOPER XL_refDate,
														  LPXLOPER XL_adjStartDate,
														  LPXLOPER XL_rollDay);

__declspec(dllexport) LPXLOPER WINAPI Local_SWAP_PRICE_TO_RATE (LPXLOPER XL_swap,
																LPXLOPER XL_date,
																LPXLOPER XL_price,
																LPXLOPER XL_model);

__declspec(dllexport) LPXLOPER WINAPI Local_SWAP_RATE_TO_PRICE (LPXLOPER XL_swap,
																LPXLOPER XL_date,
																LPXLOPER XL_rate,
																LPXLOPER XL_model);

__declspec(dllexport) LPXLOPER WINAPI Local_SWAP (LPXLOPER XL_swLeg1,
												  LPXLOPER XL_swLeg2,
												  LPXLOPER XL_minPay,
												  LPXLOPER XL_fixedRates);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_SWAP (LPXLOPER XL_swLeg1,
													  LPXLOPER XL_swLeg2,
													  LPXLOPER XL_minPay,
													  LPXLOPER XL_fixedRates);

__declspec(dllexport) LPXLOPER WINAPI Local_SwapFromExpiry (LPXLOPER XL_expiry,
															LPXLOPER XL_tenor,
															LPXLOPER XL_liborType,
															LPXLOPER XL_fixedRate,
															LPXLOPER XL_ccy);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_SwapFromExpiry (LPXLOPER XL_expiry,
																LPXLOPER XL_tenor,
																LPXLOPER XL_liborType,
																LPXLOPER XL_fixedRate,
																LPXLOPER XL_ccy);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_GetSwapLegFromSwap( LPXLOPER XL_swap,
																	LPXLOPER XL_LegNumber);

__declspec(dllexport) LPXLOPER WINAPI Local_GetSwapLegFromSwap( LPXLOPER XL_swap,
																LPXLOPER XL_LegNumber);

__declspec(dllexport) LPXLOPER WINAPI Local_CMSLEG (LPXLOPER XL_startDate,
													LPXLOPER XL_endDate,
													LPXLOPER XL_cmsType,
													LPXLOPER XL_receiveOrPay,
													LPXLOPER XL_spread,
													LPXLOPER XL_yieldDecompFreq,
													LPXLOPER XL_swapLegDayCount,
													LPXLOPER XL_resetFreq,
													LPXLOPER XL_intRule,
													LPXLOPER XL_ccy,
													LPXLOPER XL_resetTiming,
													LPXLOPER XL_payFreq,
													LPXLOPER XL_resetGap,
													LPXLOPER XL_stubRule,
													LPXLOPER XL_adjStartDate);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_CMSLEG (LPXLOPER XL_startDate,
														LPXLOPER XL_endDate,
														LPXLOPER XL_cmsType,
														LPXLOPER XL_receiveOrPay,
														LPXLOPER XL_spread,
														LPXLOPER XL_yieldDecompFreq,
														LPXLOPER XL_swapLegDayCount,
														LPXLOPER XL_resetFreq,
														LPXLOPER XL_intRule,
														LPXLOPER XL_ccy,
														LPXLOPER XL_resetTiming,
														LPXLOPER XL_payFreq,
														LPXLOPER XL_resetGap,
														LPXLOPER XL_stubRule,
														LPXLOPER XL_adjStartDate);

__declspec(dllexport) LPXLOPER WINAPI Local_REVERSEFLOAT(LPXLOPER XL_startDate,
														 LPXLOPER XL_endDate,
														 LPXLOPER XL_NotionalRatio,
														 LPXLOPER XL_receiveOrPay,
														 LPXLOPER XL_liborType,
														 LPXLOPER XL_fltCcy,
														 LPXLOPER XL_fltSpreadsId,
														 LPXLOPER XL_fltDayCount,
														 LPXLOPER XL_fxCouponsId,
														 LPXLOPER XL_extraCouponsId,
														 LPXLOPER XL_reverseCcy,
														 LPXLOPER XL_payFreq,
														 LPXLOPER XL_reverseIndexId,
														 LPXLOPER XL_fxDayCount,
														 LPXLOPER XL_multiplier,
														 LPXLOPER XL_couponFloor,
														 LPXLOPER XL_stubDate);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_REVERSEFLOAT(LPXLOPER XL_startDate,
															 LPXLOPER XL_endDate,
															 LPXLOPER XL_NotionalRatio,
															 LPXLOPER XL_receiveOrPay,
															 LPXLOPER XL_liborType,
															 LPXLOPER XL_fltCcy,
															 LPXLOPER XL_fltSpreadsId,
															 LPXLOPER XL_fltDayCount,
															 LPXLOPER XL_fxCouponsId,
															 LPXLOPER XL_extraCouponsId,
															 LPXLOPER XL_reverseCcy,
															 LPXLOPER XL_payFreq,
															 LPXLOPER XL_reverseIndexId,
															 LPXLOPER XL_fxDayCount,
															 LPXLOPER XL_multiplier,
															 LPXLOPER XL_couponFloor,
															 LPXLOPER XL_StubDate);

__declspec(dllexport) LPXLOPER WINAPI Local_CORRIDORLEG( LPXLOPER XL_startDate,
														 LPXLOPER XL_endDate,
														 LPXLOPER XL_receiveOrPay,
														 LPXLOPER XL_payIndexId,
														 LPXLOPER XL_payFreq,
														 LPXLOPER XL_spread,
														 LPXLOPER XL_refIndexId,
														 LPXLOPER XL_resetFreq,
														 LPXLOPER XL_paidRateResetTiming,
														 LPXLOPER XL_refRateResetTiming,
														 LPXLOPER XL_stubRule,
														 LPXLOPER XL_levelDownId,
														 LPXLOPER XL_downSpec,
														 LPXLOPER XL_levelUpId,
														 LPXLOPER XL_upSpec,
														 LPXLOPER XL_ccy,
														 LPXLOPER XL_MCFreq,
														 LPXLOPER XL_MCInterp,
														 LPXLOPER XL_refIndexResetGap,
                                                         LPXLOPER XL_decompPricingFlag);
                                                        

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_CORRIDORLEG( LPXLOPER XL_startDate,
															 LPXLOPER XL_endDate,
															 LPXLOPER XL_receiveOrPay,
															 LPXLOPER XL_payIndexId,
															 LPXLOPER XL_payFreq,
															 LPXLOPER XL_spread,
															 LPXLOPER XL_refIndexId,
															 LPXLOPER XL_resetFreq,
															 LPXLOPER XL_paidRateResetTiming,
															 LPXLOPER XL_refRateResetTiming,
															 LPXLOPER XL_stubRule,
															 LPXLOPER XL_levelDownId,
															 LPXLOPER XL_downSpec,
															 LPXLOPER XL_levelUpId,
															 LPXLOPER XL_upSpec,
															 LPXLOPER XL_ccy,
															 LPXLOPER XL_MCFreq,
															 LPXLOPER XL_MCInterp,
															 LPXLOPER XL_refIndexResetGap,
                                                             LPXLOPER XL_decompPricingFlag);
                                                            

__declspec(dllexport) LPXLOPER WINAPI Local_CORRIDORLEG_WITHCALENDARS( LPXLOPER XL_startDate,
																	   LPXLOPER XL_endDate,
																	   LPXLOPER XL_receiveOrPay,
																	   LPXLOPER XL_payIndexId,
																	   LPXLOPER XL_payFreq,
																	   LPXLOPER XL_spread,
																	   LPXLOPER XL_refIndexId,
																	   LPXLOPER XL_resetFreq,
																	   LPXLOPER XL_paidRateResetTiming,
																	   LPXLOPER XL_refRateResetTiming,
																	   LPXLOPER XL_stubRule,
																	   LPXLOPER XL_levelDownId,
																	   LPXLOPER XL_downSpec,
																	   LPXLOPER XL_levelUpId,
																	   LPXLOPER XL_upSpec,
																	   LPXLOPER XL_ccy,
																 	   LPXLOPER XL_ResetCal,
																	   LPXLOPER XL_PayCal,
																	   LPXLOPER XL_decompPricingFlag,
                                                                       LPXLOPER XL_refIndexResetGap);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_CORRIDORLEG_WITHCALENDARS( LPXLOPER XL_startDate,
																		   LPXLOPER XL_endDate,
																		   LPXLOPER XL_receiveOrPay,
																		   LPXLOPER XL_payIndexId,
																		   LPXLOPER XL_payFreq,
																		   LPXLOPER XL_spread,
																		   LPXLOPER XL_refIndexId,
																		   LPXLOPER XL_resetFreq,
																		   LPXLOPER XL_paidRateResetTiming,
																		   LPXLOPER XL_refRateResetTiming,
																		   LPXLOPER XL_stubRule,
																		   LPXLOPER XL_levelDownId,
																		   LPXLOPER XL_downSpec,
																		   LPXLOPER XL_levelUpId,
																		   LPXLOPER XL_upSpec,
																		   LPXLOPER XL_ccy,
																		   LPXLOPER XL_ResetCal,
																		   LPXLOPER XL_PayCal,
																		   LPXLOPER XL_decompPricingFlag,
                                                                           LPXLOPER XL_refIndexResetGap);

__declspec(dllexport) LPXLOPER WINAPI Local_RESTRIKABLELEG(LPXLOPER XL_startDate,
														   LPXLOPER XL_endDate,
														   LPXLOPER XL_receiveOrPay,
														   LPXLOPER XL_payIndexId,
														   LPXLOPER XL_spread,
														   LPXLOPER XL_refIndexId,
														   LPXLOPER XL_stubRule,
														   LPXLOPER XL_range,
														   LPXLOPER XL_ccy,
														   LPXLOPER XL_Alpha,
														   LPXLOPER XL_Beta,
                                                           LPXLOPER XL_decompPricingFlag,
														   LPXLOPER XL_AdjStartDateFlag);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_RESTRIKABLELEG(LPXLOPER XL_startDate,
															   LPXLOPER XL_endDate,
															   LPXLOPER XL_receiveOrPay,
															   LPXLOPER XL_payIndexId,
															   LPXLOPER XL_spread,
															   LPXLOPER XL_refIndexId,
															   LPXLOPER XL_stubRule,
															   LPXLOPER XL_range,
															   LPXLOPER XL_ccy,
															   LPXLOPER XL_Alpha,
															   LPXLOPER XL_Beta,
                                                               LPXLOPER XL_decompPricingFlag,
															   LPXLOPER XL_AdjStartDateFlag);

__declspec(dllexport) LPXLOPER WINAPI Local_CMTLEG (LPXLOPER XL_startDate,
													LPXLOPER XL_endDate,
													LPXLOPER XL_cmtType,
													LPXLOPER XL_bondCouponFreq,
													LPXLOPER XL_bondDayCount,
													LPXLOPER XL_receiveOrPay,
													LPXLOPER XL_spread,
													LPXLOPER XL_yieldDecompFreq,
													LPXLOPER XL_swapLegDayCount,
													LPXLOPER XL_intRule,
													LPXLOPER XL_resetGap,
													LPXLOPER XL_resetFreq,
													LPXLOPER XL_ntlAmount,
													LPXLOPER XL_ccy,
													LPXLOPER XL_resetTiming,
													LPXLOPER XL_adjStartDate);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_CMTLEG (LPXLOPER XL_startDate,
														LPXLOPER XL_endDate,
														LPXLOPER XL_cmtType,
														LPXLOPER XL_bondCouponFreq,
														LPXLOPER XL_bondDayCount,
														LPXLOPER XL_receiveOrPay,
														LPXLOPER XL_spread,
														LPXLOPER XL_yieldDecompFreq,
														LPXLOPER XL_swapLegDayCount,
														LPXLOPER XL_intRule,
														LPXLOPER XL_resetGap,
														LPXLOPER XL_resetFreq,
														LPXLOPER XL_ntlAmount,
														LPXLOPER XL_ccy,
														LPXLOPER XL_resetTiming,
														LPXLOPER XL_adjStartDate);

__declspec(dllexport) LPXLOPER WINAPI Local_TMLEG(LPXLOPER XL_tmIxType,
												  LPXLOPER XL_startDate,
												  LPXLOPER XL_endDate,
												  LPXLOPER XL_receiveOrPay,
                                                  LPXLOPER XL_spread
                                                  LPXLOPER XL_payFreq,
                                                  LPXLOPER XL_resetFreq,
                                                  LPXLOPER XL_intRule,
                                                  LPXLOPER XL_fwdRule,
												  LPXLOPER XL_stubRule,
                                                  LPXLOPER XL_ccy);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_TMLEG(LPXLOPER XL_tmIxType,
													  LPXLOPER XL_startDate,
													  LPXLOPER XL_endDate,
													  LPXLOPER XL_receiveOrPay,
													  LPXLOPER XL_spread,
                                                      LPXLOPER XL_payFreq,
                                                      LPXLOPER XL_resetFreq,
                                                      LPXLOPER XL_intRule,
                                                      LPXLOPER XL_fwdRule,
													  LPXLOPER XL_stubRule,
                                                      LPXLOPER XL_ccy);

__declspec(dllexport) LPXLOPER WINAPI Local_IMPLIEDSPREAD (LPXLOPER XL_swap,
														   LPXLOPER XL_model,
														   LPXLOPER XL_price,
														   LPXLOPER XL_leg1Or2);

__declspec(dllexport) LPXLOPER WINAPI Local_ARM_GenAmortization(LPXLOPER XL_swapleg,
																LPXLOPER XL_amortMethod,
																LPXLOPER XL_amortFrequency,
																LPXLOPER XL_amortAmount,
																LPXLOPER XL_basisDaycount,
																LPXLOPER XL_legNotional,
																LPXLOPER XL_amortRate,
																LPXLOPER XL_reducedMaturity,
																LPXLOPER XL_modelId,
																LPXLOPER XL_cleanup);
__declspec(dllexport) LPXLOPER WINAPI local_PXL_ARM_GenAmortization(LPXLOPER XL_swapleg,
																	LPXLOPER XL_amortMethod,
																	LPXLOPER XL_amortFrequency,
																	LPXLOPER XL_amortAmount,
																	LPXLOPER XL_basisDaycount,
																	LPXLOPER XL_legNotional,
																	LPXLOPER XL_amortRate,
																	LPXLOPER XL_reducedMaturity,
																	LPXLOPER XL_modelId);

__declspec(dllexport) LPXLOPER WINAPI Local_SWAP_WITH_NOTIONNAL (LPXLOPER XL_swLeg1,
																 LPXLOPER XL_swLeg2,
																 LPXLOPER XL_not,
																 LPXLOPER XL_minPay);
__declspec(dllexport) LPXLOPER WINAPI Local_PXL_SWAP_WITH_NOTIONNAL (LPXLOPER XL_swLeg1,
																	 LPXLOPER XL_swLeg2,
																	 LPXLOPER XL_not,
																	 LPXLOPER XL_minPay);

__declspec(dllexport) LPXLOPER WINAPI Local_ARM_CUSTOMFIRSTDATE (LPXLOPER XL_swlegId,
																 LPXLOPER XL_date);


__declspec(dllexport) LPXLOPER WINAPI Local_ARM_GENERALLEG (LPXLOPER XL_startDate,
															LPXLOPER XL_endDate,
															LPXLOPER XL_type,
															LPXLOPER XL_liborType,
															LPXLOPER XL_rcvOrPay,
															LPXLOPER XL_fixRate,
															LPXLOPER XL_daycount,
															LPXLOPER XL_resetFreq,
															LPXLOPER XL_payFreq,
															LPXLOPER XL_decompFreq,
															LPXLOPER XL_resetTiming,
															LPXLOPER XL_payTiming,
															LPXLOPER XL_intRule,
															LPXLOPER XL_stubRule,
															LPXLOPER XL_resetGap,
															LPXLOPER XL_currency,
															LPXLOPER XL_resetcal,
															LPXLOPER XL_paycal,
															LPXLOPER XL_decompPricingFlag,
															LPXLOPER XL_nxChange);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_ARM_GENERALLEG (LPXLOPER XL_startDate,
																LPXLOPER XL_endDate,
																LPXLOPER XL_liborType,
																LPXLOPER XL_rcvOrPay,
																LPXLOPER XL_fixRate,
																LPXLOPER XL_daycount,
																LPXLOPER XL_resetFreq,
																LPXLOPER XL_payFreq,
																LPXLOPER XL_decompFreq,
																LPXLOPER XL_resetTiming,
																LPXLOPER XL_payTiming,
																LPXLOPER XL_intRule,
																LPXLOPER XL_stubRule,
																LPXLOPER XL_resetGap,
																LPXLOPER XL_currency,
																LPXLOPER XL_resetcal,
																LPXLOPER XL_paycal,
																LPXLOPER XL_decompPricingFlag,
																LPXLOPER XL_nxChange);

__declspec(dllexport) LPXLOPER WINAPI Local_REVERSESTICKYLEG (LPXLOPER XL_startDate,
															  LPXLOPER XL_endDate,
															  LPXLOPER XL_liborType,
															  LPXLOPER XL_receiveOrPay,
															  LPXLOPER XL_spreads,
															  LPXLOPER XL_strikes,
															  LPXLOPER XL_first_coupon,
															  LPXLOPER XL_resetFreq,
															  LPXLOPER XL_payFreq,
															  LPXLOPER XL_resetTiming,
															  LPXLOPER XL_payTiming,
															  LPXLOPER XL_ccy);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_REVERSESTICKYLEG (LPXLOPER XL_startDate,
																  LPXLOPER XL_endDate,
																  LPXLOPER XL_liborType,
																  LPXLOPER XL_receiveOrPay,
																  LPXLOPER XL_spreads,
																  LPXLOPER XL_strikes,
																  LPXLOPER XL_first_coupon,
																  LPXLOPER XL_resetFreq,
																  LPXLOPER XL_payFreq,
																  LPXLOPER XL_resetTiming,
																  LPXLOPER XL_payTiming,
																  LPXLOPER XL_ccy);

__declspec(dllexport) LPXLOPER WINAPI Local_IMPLIEDSPREADWITHMODELS (LPXLOPER XL_swap,
																	 LPXLOPER XL_model1,
																	 LPXLOPER XL_model2,
																	 LPXLOPER XL_price,
																	 LPXLOPER XL_leg1Or2);

__declspec(dllexport) LPXLOPER WINAPI Local_ARM_SetLastFixing(LPXLOPER XL_securityId,
															  LPXLOPER XL_rate,
                                                              LPXLOPER XL_FixingBeforeLast,
															  LPXLOPER XL_asof,
															  LPXLOPER XL_resetDate);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_ARM_SetLastFixing(LPXLOPER XL_securityId,
																  LPXLOPER XL_rate,
																  LPXLOPER XL_FixingBeforeLast,
																  LPXLOPER XL_asof,
																  LPXLOPER XL_resetDate);

__declspec(dllexport) LPXLOPER WINAPI Local_ARM_SetFixRates(LPXLOPER XL_securityId,
															LPXLOPER XL_fixRates);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_ARM_SetFixRates(LPXLOPER XL_securityId,
																LPXLOPER XL_fixRates);

__declspec(dllexport) LPXLOPER WINAPI Local_ARM_GENLEG (LPXLOPER XL_startDates,
														LPXLOPER XL_endDates,
														LPXLOPER XL_paymentDates,
														LPXLOPER XL_resetDates,
														LPXLOPER XL_intDays,
														LPXLOPER XL_notional,
														LPXLOPER XL_irIndex,
														LPXLOPER XL_rcvOrPay,
														LPXLOPER XL_fixRateOrSpread,
														LPXLOPER XL_fwdOrFixing,
														LPXLOPER XL_ccy,
														LPXLOPER XL_nxChange,
														LPXLOPER XL_couponDayCount);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_ARM_GENLEG (LPXLOPER XL_startDates,
															LPXLOPER XL_endDates,
															LPXLOPER XL_paymentDates,
															LPXLOPER XL_resetDates,
															LPXLOPER XL_intDays,
															LPXLOPER XL_notional,
															LPXLOPER XL_irIndex,
															LPXLOPER XL_rcvOrPay,
															LPXLOPER XL_fixRateOrSpread,
															LPXLOPER XL_fwdOrFixing,
															LPXLOPER XL_ccy,
															LPXLOPER XL_nxChange,
															LPXLOPER XL_couponDayCount);

__declspec(dllexport) LPXLOPER WINAPI Local_SWAPLEG2 (LPXLOPER XL_irIndex,
													 LPXLOPER XL_startDate,
													 LPXLOPER XL_endDate,
													 LPXLOPER XL_receiveOrPay,
													 LPXLOPER XL_spread,
													 LPXLOPER XL_ccy,
													 LPXLOPER XL_dayCount,
													 LPXLOPER XL_resetTiming,
                                                     LPXLOPER XL_resetGap,
													 LPXLOPER XL_payTiming,
                                                     LPXLOPER XL_payGap,
													 LPXLOPER XL_decompPricingFlag);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_SWAPLEG2 (LPXLOPER XL_irIndex,
												         LPXLOPER XL_startDate,
												         LPXLOPER XL_endDate,
												         LPXLOPER XL_receiveOrPay,
												         LPXLOPER XL_spread,
												         LPXLOPER XL_ccy,
												         LPXLOPER XL_dayCount,
												         LPXLOPER XL_resetTiming,
                                                         LPXLOPER XL_resetGap,
												         LPXLOPER XL_payTiming,
                                                         LPXLOPER XL_payGap,
												         LPXLOPER XL_decompPricingFlag);


__declspec(dllexport) LPXLOPER WINAPI Local_LIVRETALEG(LPXLOPER XL_startDate,
													  LPXLOPER XL_endDate,
													  LPXLOPER XL_receiveOrPay,
													  LPXLOPER XL_spread,
													  LPXLOPER XL_resetFreq,
													  LPXLOPER XL_payFreq,
													  LPXLOPER XL_resetTiming,
													  LPXLOPER XL_payTiming,
													  LPXLOPER XL_ccy,
													  LPXLOPER XL_intRule,
													  LPXLOPER XL_resetGap,
													  LPXLOPER XL_resetCal,
													  LPXLOPER XL_payCal,
													  LPXLOPER XL_decompPricingFlag,
													  LPXLOPER XL_nxChange,
													  LPXLOPER XL_stubRule,
													  LPXLOPER XL_refDate,
													  LPXLOPER XL_adjStartDate,
													  LPXLOPER XL_daycount);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_LIVRETALEG( LPXLOPER XL_startDate,
															LPXLOPER XL_endDate,
															LPXLOPER XL_receiveOrPay,
															LPXLOPER XL_spread,
															LPXLOPER XL_resetFreq,
															LPXLOPER XL_payFreq,
															LPXLOPER XL_resetTiming,
															LPXLOPER XL_payTiming,
															LPXLOPER XL_ccy,
															LPXLOPER XL_intRule,
															LPXLOPER XL_resetGap,
															LPXLOPER XL_resetCal,
															LPXLOPER XL_payCal,
															LPXLOPER XL_decompPricingFlag,
															LPXLOPER XL_nxChange,
															LPXLOPER XL_stubRule,
															LPXLOPER XL_refDate,
															LPXLOPER XL_adjStartDate,
															LPXLOPER XL_daycount);

__declspec(dllexport) LPXLOPER WINAPI Local_AVERAGE_LIBOR_LEG(	LPXLOPER XL_irIndex,
																LPXLOPER XL_startDate,
																LPXLOPER XL_endDate,
																LPXLOPER XL_receiveOrPay,
																LPXLOPER XL_spread,
																LPXLOPER XL_ccy,
																LPXLOPER XL_dayCount,
																LPXLOPER XL_payCal,
																LPXLOPER XL_decompPricingFlag,
																LPXLOPER XL_nxChange,
																LPXLOPER XL_stubRule,
																LPXLOPER XL_refDate,
																LPXLOPER XL_adjStartDate,
																LPXLOPER XL_couru);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_AVERAGE_LIBOR_LEG (	LPXLOPER XL_irIndex,
																	LPXLOPER XL_startDate,
																	LPXLOPER XL_endDate,
																	LPXLOPER XL_receiveOrPay,
																	LPXLOPER XL_spread,
																	LPXLOPER XL_ccy,
																	LPXLOPER XL_dayCount,
																	LPXLOPER XL_payCal,
																	LPXLOPER XL_decompPricingFlag,
																	LPXLOPER XL_nxChange,
																	LPXLOPER XL_stubRule,
																	LPXLOPER XL_refDate,
																	LPXLOPER XL_adjStartDate,
																	LPXLOPER XL_couru);

__declspec(dllexport) LPXLOPER WINAPI Local_UnderSwapFromBermuda(	LPXLOPER XL_swaption,
																	LPXLOPER XL_NDIndex);

__declspec(dllexport) LPXLOPER WINAPI Local_PXL_UnderSwapFromBermuda(	LPXLOPER XL_swaption,
																		LPXLOPER XL_NDIndex);


#endif	/* ARM_XL_SWAP_LOCAL_H */

/*---- End Of File ----*/
/* EOF %M% */ 
