/////////////////////////////////////////////////////////////////////////////
// Name:        ihg/xml/calibrationreader.h
// Purpose:     reading calibration XML files
// Author:      ITo33
// Created:     2004/12/01
// RCS-ID:      $Id: calibrationreader.h,v 1.5 2005/07/18 15:07:19 dave Exp $
// Copyright:   (c) 2004- Trilemma LLP
/////////////////////////////////////////////////////////////////////////////

/**
    @file ihg/xml/calibrationreader.h
    @brief Classes for reading calibration XML-files generated by IHG.
 */

#ifndef _ITO33_IHG_XML_CALIBRATIONREADER_H_
#define _ITO33_IHG_XML_CALIBRATIONREADER_H_

#include "ito33/xml/reader.h"

namespace ito33
{

namespace finance
{
  class DerivativeVisitor;
  class TermStructureEnumerator;
  class Derivatives;
}

namespace ihg
{

class ParametrizationVisitor;

namespace XML
{

/**
    This class reads calibration XML documents and provides easy access to the 
    data in them.

    Right now XML data can only be loaded from a file but we could also load it
    from a string if needed. Unfortunately, xmlwrapp doesn't take std::istream
    as input...
 */
class CalibrationReader : public ito33::XML::Reader
{
public:
 
  /**
    Load XML from the given file.

    If an error occurs while loading date, i.e. file is not found, couldn't be
    read or doesn't contain a valid XML document with the IHG roto tag, an
    exception is thrown.

    @param filename the name of the file to read XML from
   */
  CalibrationReader(const char *filename)
    : ito33::XML::Reader(filename)
  {}

  // Default dtor OK

  /**
    Fill in the passed in calibration object with the data from XML.

    @param visitor filled in with information we read from node
   */
  void ReadCalibration(ParametrizationVisitor& param_visitor,
                       finance::TermStructureEnumerator& termstructures,
                       finance::DerivativeVisitor& deriv_visitor,
                       finance::Derivatives& derivatives) const;

private:

  NO_COPY_CLASS(CalibrationReader);
};

} // namespace XML

} // namespace ihg

} // namespace ito33

#endif // _ITO33_IHG_XML_CALIBRATIONREADER_H_
