
#include "ito33/link.h"


ITO33_FORCE_LINK_MODULE(IHGPriceOption);
ITO33_FORCE_LINK_MODULE(IHGPriceCDS);
ITO33_FORCE_LINK_MODULE(IHGPriceCB);
ITO33_FORCE_LINK_MODULE(IHGPriceBond);
ITO33_FORCE_LINK_MODULE(IHGPriceReset);
ITO33_FORCE_LINK_MODULE(IHGPriceGeneralizedPEPSLike);
ITO33_FORCE_LINK_MODULE(IHGPriceAttachedWarrantConvertibleBond);
