#ifndef ARM_MOD_H
#define ARM_MOD_H



#include "ARM_result.h"



extern long ARM_bsslmodel(double startDate,
						  long zc_type,
						  double zc,
						  long volSpreadLock_type,
						  double volSpreadLock,
						  long capVol_type,
						  double capVol,
						  long indexVol_type,
						  double indexVol,
						  ARM_result& result,
						  long objId = -1);

extern long ARM_bsmodel(double date,
						double spot,
						long dividend_type,
						double dividend,
						long discrate_type,
						double discrate,
						long volat_type,
						double volat,
						long typstk,
						ARM_result& result,
						long objId = -1);

extern long ARM_ycmod(long zerocurveId,
					  long discCurveId,
					  ARM_result& result,
					  long objId = -1);

extern long ARM_GetParameter(long modId,
							 long paraId,
							 ARM_result& result);

extern long ARM_HWTREE(long zcId,
					   double begDate,
					   double endDate,
                       long nbSteps,
					   double a,
                       double sigma,
					   ARM_result& result,
					   long objId = -1);

extern long ARM_LDCMC_FROM_ANA(long anaModId,
							   double horizon,
                               long nbTraj,
							   long mcmethod,
							   long pricerTypeId,
                               ARM_result& result,
							   long objId = -1);

extern long ARM_HWSIGCONST(long zcId,
						   double begDate,
						   double endDate,
                           long nbSteps,
						   double a,
                           double sigma, 
                           ARM_result& result,
						   long objId = -1);

extern long ARM_CRRTREE(double begDate,
						double endDate,
                        long nbSteps,
						double spot,
                        double dividend,
						double discrate,
                        double volat,
                        ARM_result& result,
						long objId = -1);

extern long ARM_GYCMODEL(long zcId,
                         double a, 
                         double sigma, 
                         ARM_result& result,
						 long objId = -1);

extern long ARM_HWTWOFACTMOD(long zcId,
                             double a, 
                             double sigma1,
                             double b,
                             double sigma2,
                             double rho,
                             ARM_result& result,
							 long objId = -1);

extern long ARM_IDTREEHW(double startDate,
						 double horizon,
						 long nbSteps,
                         double dMeanRevSpeed,
						 double fMeanRevSpeed,
                         double dSigma,
						 double fSigma,
                         double prtyCorr,
						 double prtyVol,
                         double ratesCorr, 
                         long   dZcId,
						 long fZcId,
                         ARM_result& result,
						 long objId = -1);

extern long ARM_LDCANA(long zcId, 
                       const VECTOR<CCString>& resetDates, 
                       const VECTOR<double>& shifts,
                       const VECTOR<double>& vols,
                       ARM_result& result,
					   long objId = -1);

extern long ARM_HWSIGVAR(long zcId,
                         long begDate,
						 long endDate,
                         long nbSteps,
						 double a,
						 long real_size,
                         const VECTOR<CCString>& dates,
						 const VECTOR<double>& sigmas,
                         ARM_result& result,
						 long objId = -1);

extern long ARM_HWANALYTICSIGVAR(long zcId, 
                                 double a,
								 long real_size,
                                 const VECTOR<CCString>& dates, 
                                 const VECTOR<double>& sigmas,
                                 ARM_result& result,
								 long objId = -1);

extern long ARM_GYCLSMODEL (long curveId,
							double a,
							double sigma,
							double solv,
							double solvVol,
							double solvRCorr,
							double lossRate,
							ARM_result& result,
							long objId = -1);

extern long ARM_GTWOYC (double dMeanRevSpeed,
						double dSigma,
						long dZcId,
						long fZcId,
						double ratesCorr,
						double fMeanRevSpeed,
						double fSigma,
						ARM_result& result,
						long objId = -1);

extern long ARM_ARM_COVAR (long modId,
						   double maturity1,
						   double maturity2,
						   ARM_result& result);

extern long ARM_ARM_CORREL (long modId,
							double maturity1,
							double maturity2,
							ARM_result& result);

extern long ARM_HWTWOFFNMONTECARLOSV (long zcId,
									  double horizon,
									  double a,
									  double b,
									  double sigmaRatio,
									  double rho,
									  const VECTOR<double>& sigmaDate,
									  const VECTOR<double>& sigmaVal,
									  long nbTraj,
									  ARM_result& result,
									  long objId = -1);

extern long ARM_HWTWOFTREE (long zcId,
							double dateDeb,
							double dateFin,
							long pas,
							double a,
							double sig1,
							double b,
							double sig2,
							double rho,
							ARM_result& result,
							long objId = -1);

extern long ARM_HWFNMONTECARLOSV (long zcId,
								  double horizon,
								  double a,
								  const VECTOR<double>& sigmaDate,
								  const VECTOR<double>& sigmaVal,
								  long nbTraj,
								  ARM_result& result,
								  long objId = -1);

extern long ARM_HWFNMONTECARLO (long zcId,
							    double horizon,
								double a,
								double sigma,
								long nbTraj,
								ARM_result& result,
								long objId = -1);

extern long ARM_HWTWOFANALYTICSIGVAR (long zcId, 
									  double a,
									  double b,
									  double rho,
									  double sigmaRatio,
									  long real_size,
									  const VECTOR<CCString>& dates, 
									  const VECTOR<double>& sigmas,
									  ARM_result& result,
									  long objId = -1);

extern long ARM_DFBS (long dVolId,
					  long fVolId,
					  long dZcId,
					  long fZcId,
					  double fxCorr,
					  double fxVol,
					  double ratesCorr,
					  long dTypVol,
					  long fTypVol,
					  ARM_result& result,
					  long objId = -1);

extern long ARM_DFFXBS (long dVolId,
						long fVolId,
						long dZcId,
						long fZcId,
						long dFxCorrId,
						long fFxCorrId,
						long fxVolId,
						double ratesCorr,
						long dBSZcId,
						long fBSZcId,
						double spot,
						ARM_result& result,
						long objId = -1);

extern long ARM_DFGYC (double dMeanRevSpeed,
					   double fMeanRevSpeed,
					   double dSigma,
				 	   double fSigma,
					   double fxCorr,
					   double fxVol,
					   double ratesCorr,
					   long dZcId,
					   long fZcId,
					   ARM_result& result,
					   long objId = -1);

extern long ARM_DFFXBSPLAIN (long dVolId,
							 long fVolId,
							 long dZcId,
							 long fZcId,
							 double dFxCorr,
							 double fFxCorr,
							 double fxVol,
							 double ratesCorr,
							 ARM_result& result,
							 long objId = -1);

extern long ARM_DFHWXSIGVAR (long dZcId,
							 long fZcId,
							 double dMeanRevSpeed,
							 double fMeanRevSpeed,
							 const VECTOR<double>& dDate,
							 const VECTOR<double>& fDate,
							 const VECTOR<double>& dSigma,
							 const VECTOR<double>& fSigma,
							 long dFxCorrId,
							 long fFxCorrId,
							 long fxVolId,
							 double ratesCorr,
							 ARM_result& result,
							 long objId = -1);

extern long ARM_DFHWSIGVARTREE (double startDate,
								double horizon,
								long numSteps,
								long dZcId,
								long fZcId,
								double dMeanRevSpeed,
								const VECTOR<double>& dDate,
								const VECTOR<double>& dSigma,
								double fMeanRevSpeed,
								const VECTOR<double>& fDate,
								const VECTOR<double>& fSigma,
								long dFxCorrId,
								long fFxCorrId,
								long fxVolId,
								double ratesCorr,
								double fxSpotRate,
								ARM_result& result,
								long objId = -1);

extern long ARM_BKIRTREE (long zcId,
						  double startDate,
					      double endDate,
					      long pas,
					      double a,
					      double sigma,
					      ARM_result& result,
					      long objId = -1);



extern long ARM_FRMTREE(long FrmAnaId,
						double horizon,
						long fineMonth,
						const VECTOR<double>& corrMatu,
						const VECTOR<double>& corrMatrix,
						const VECTOR<double>& corr2Matu,
						ARM_result& result,
						long objId = -1);


extern long ARM_FRMTREE_AUTO(long zcId,
							 long volId,
							 long smileId,
							 long autoMode,
							 double horizon,
							 long fineMonth,
							 double shapeDecay,
							 double shapeSlope,
							 double shapeAsymptote,
							 long nbFactor,
							 const VECTOR<double>& corrMatu,
							 const VECTOR<double>& corrMatrix,
							 const VECTOR<double>& corr2Matu,
							 ARM_result& result,
							 long objId = -1);

extern long ARM_FRMTREE_AUTO_G(long zcId,
							   long zdId,
							   long volId,
							   long smileId,
							   long irgvolId,
							   long irgsmileId,
							   long autoModeId,
							   double horizon,
							   long fineMonthId,
							   double shapeDecay,
							   double shapeSlope,
							   double shapeAsymptote,
							   long nbFactor,
							   const VECTOR<double>& corrMatu,
							   const VECTOR<double>& corrMatrix,
							   const VECTOR<double>& corr2Matu,
							   ARM_result& result,
							   long objId = -1);

extern long ARM_FRMTREE_AUTO_B(long zcId,
							   long zdId,
							   long volId, 
							   long smileId,
							   long autoModeId,
							   double horizon,
							   long fineMonthId,
							   double shapeDecay,
							   double shapeSlope,
							   double shapeAsymptote,
							   long nbFactor,
							   const VECTOR<double>& corrMatu,
							   const VECTOR<double>& corrMatrix,
							   const VECTOR<double>& corr2Matu,
							   ARM_result& result,
							   long objId = -1);

extern long ARM_FRMANA(long zcId,
					   const VECTOR<CCString>& resetDates,
					   const VECTOR<double>&   spotVols,
					   long shapeType,
					   double shapeDecay,
					   double shapeSlope,
					   double shapeAsymptote,
					   long nbFactor,
					   const VECTOR<double>& corrMatu,
					   const VECTOR<double>& corrMatrix,
					   const VECTOR<double>& corr2Matu,
					   ARM_result& result,
					   long objId = -1);

extern long ARM_FRMANA_PORT(long zcId,
							long portId,
							const VECTOR<CCString>& resetDates,
							double precision,
							double min_paras,
							double max_paras,
							long   max_iters,
							long shapeType,
							double shapeDecay,
							double shapeSlope,
							double shapeAsymptote,
							long nbFactor,
							const VECTOR<double>& corrMatu,
							const VECTOR<double>& corrMatrix,
							const VECTOR<double>& corr2Matu,
							ARM_result& result,
							long objId = -1);

extern long ARM_FRMLSMC(long FrmAnaId,
						double horizon,
						long nbTraj,
						long fineMonth,
						long mcMethod,
						const VECTOR<double>& corrMatu,
						const VECTOR<double>& corrMatrix,
						const VECTOR<double>& corr2Matu,
						ARM_result& result,
						long objId = -1);

extern long ARM_FRMLSMC_AUTO(long zcId,
							 long volId,
							 long smileId,
							 long autoModeId,
							 double horizon,
							 long fineMonthId,
							 long   nbTraj,
							 long mcMethod,
							 long noControl,
							 double shapeDecay,
							 double shapeSlope,
							 double shapeAsymptote,
							 long nbFactor,
							 const VECTOR<double>& corrMatu,
							 const VECTOR<double>& corrMatrix,
							 const VECTOR<double>& corr2Matu,
							 ARM_result& result,
							 long objId = -1);

extern long ARM_BASISMCFRM(long   zcId, 
					       long   baZcId,
                           long   volId, 
                           long   smileId,
                           long   productType,
                           double horizon,
                           long   nbTraj,
                           long   MCGeneratorType,
                           double shapeDecay,
                           double shapeSlope,
                           double shapeAsymptote,
                           long   nbFactor,
                           const  VECTOR<double>& indexes,
                           const  VECTOR<double>& correlatedIndex,
                           const  VECTOR<double>& corrMatrix,
					       long   control,
					       long   seed,
                           ARM_result& result,
						   long objId = -1);

extern long ARM_BASISMCFRM2CR(long   zcId,
							  long   baZcId,
							  long   swoptvolId,
							  long   swoptsmileId,
							  long   irgvolId,
							  long   irgsmileId,
							  long   productType,
							  double horizon,
							  long   nbTraj,
							  long   MCGeneratorType,
							  double shapeDecay,
							  double shapeSlope,
							  double shapeAsymptote,
							  long   nbFactor,
							  const  VECTOR<double>& indexes,
							  const  VECTOR<double>& correlatedIndex,
							  const  VECTOR<double>& corrMatrix,
							  long   control,
							  long   seed,
							  ARM_result& result,
							  long objId = -1);

extern long ARM_FRMLSMC_AUTO_2(long zcId, 
                               long swoptVolId, 
                               long swoptSmileId,
                               long irgVolId, 
                               long irgSmileId,
                               long autoMode,
                               double horizon,
                               long fineMonth,
                               long nbTraj,
                               long mcMethod,
                               long noControl,
                               double shapeDecay,
                               double shapeSlope,
                               double shapeAsymptote,
                               long nbFactor,
                               const VECTOR<double>& corrMatu,
                               const VECTOR<double>& corrMatrix,
                               const VECTOR<double>& corr2Matu,
                               ARM_result& result,
							   long objId = -1);

extern long ARM_FRMLSMC_AUTO_G(long zcId,
							   long zdId,
							   long swoptVolId,
							   long swoptSmileId,
							   long irgVolId,
							   long irgSmileId,
							   long intAutoMode,
							   double horizon,
							   long fineMonth,
							   long nbTraj,
							   long mcMethod,
							   long noControl,
							   double shapeDecay,
							   double shapeSlope,
							   double shapeAsymptote,
							   long nbFactor,
							   const VECTOR<double>& corrMatu,
							   const VECTOR<double>& corrMatrix,
							   const VECTOR<double>& corr2Matu,
							   ARM_result& result,
							   long objId = -1);

extern long ARM_SMILEDLDCMC(long anaModId,
							double horizon,
							long nbTraj,
							double dVolSpot,
							double Asymp_Row,
							double Asymp_Col,
							double pUp,
							double pDown,
							long mcmethod,
							ARM_result& result,
							long objId = -1);

extern long ARM_FITTEDSMILEDLDCMC(long anaModId,
								  double horizon,
								  long nbTraj,
								  long volBSId,
								  long volSmileId,
								  double strike1,
								  double strike2,
								  double Asymp_Row,
								  long mcmethod,
								  ARM_result& result,
								  long objId = -1);

extern long ARM_SMILEDLDCANA(long anaModId,
							 double dVolSpotUp,
							 double Asymp_RowUp,
							 double Asymp_ColUp,
							 double pUp,
							 double dVolSpotDo,
							 double Asymp_RowDo,
							 double Asymp_ColDo,
							 double pDo,
							 ARM_result& result,
							 long objId = -1);

extern long ARM_SMILEDLDCFROMANA(long anaModId,
								 double horizon,
								 long nbTraj,
								 long mcmethod,
								 ARM_result& result,
								 long objId = -1);

extern long ARM_GLOBDFBS(long DomBSId,
						 long DomCurrId,
						 long FrgBSId,
						 long FrgCurrId,
						 long fxVolCrvId,
						 long FFxCorrId,
						 long RatesCorrId,
						 ARM_result& result,
						 long objId = -1);
 
extern long ARM_bssmiledmodel(double date,
							  double spot,
							  long dividend_type,
							  double dividend,
							  long discrate_type,
							  double discrate,
							  long volat_type,
							  double volat,
							  long typstk,
							  const VECTOR<double>& matu,
							  long betaType,
							  long betaObj,
							  const VECTOR<double>& beta,
							  long omegaType,
							  long omegaObj,
							  const VECTOR<double>& omega,
							  long isSABR,
							  ARM_result& result,
							  long objId = -1);

extern long ARM_BSCORRMODEL(double startDate,
							long zcId,
							long spreadlockId,
							long capirgvolId,
							long capcashvolId,
							long indexadjvolId,
							long spreadvolId,
							long correlationsId,
							long modelTypeId,
							long volTypeId,
							ARM_result& result,
							long objId = -1);

extern long ARM_ARM_GetComputedSigmaSABR(long modId,
										 ARM_result& result);

extern long ARM_ARM_HWSIGVARFROMANA(long modId,
									long endDate,
									long nbSteps,
									ARM_result& result,
									long objId = -1);

extern long ARM_ARM_CALIBRATIONHWSV(double asof,
									long zcId,
									long volId,
									long secId,
									double amin,
									double amax,
									double volmin,
									double volmax,
									const VECTOR<CCString>& dates,
									long pfId,
									ARM_result& result,
									long objId = -1);

extern long ARM_ARM_CALIBRATE (long calibId,
								long calibType,
								ARM_result& result,
								long objId = -1);

extern long ARM_ARM_BSSMILEDCALIBRATE(long modelId,
									  long pfId,
									  long calVolOrNotId,
									  long calRhoOrNotId,
									  long calNuOrNotId,
									  double volTenor,
									  double timeStep,
									  double minSig,
									  double maxSig,
									  double minRho,
									  double maxRho,
									  double minNu,
									  double maxNu,
									  long interpMethodId,
									  double tol,
									  long maxIter,
									  long gradCalcId,
									  double lambda,
									  long globOrBootstrapId,
									  double beginSmoothMatu,
									  ARM_result& result,
									  long objId = -1);

extern long ARM_ARM_GETCALIBRATED_SIGRHONU(long modelId,
										   long paramId,
										   ARM_result& result,
										   long objId = -1);

extern long ARM_ARM_FRMMARKOVTREE(double startDate,
								  double horizon,
								  long zcId,
								  long PathNumber,
								  const VECTOR<double>& Params,
								  long FRMModelId,
								  ARM_result& result,
								  long objId = -1);

extern long ARM_ARM_CalibrationFRMModel(long zcId,
										long pf1Id,
                                        long pf2Id,
										long nbFactors,
										long liborTypeId,
										const VECTOR<double>& powers,
										const VECTOR<double>& smoothParams,
										const VECTOR<double>& ACalibrationSchedule,
										const VECTOR<double>& KCalibrationSchedule,
										long initA,
										long initK,
										const VECTOR<double>& meanRevA,
										const VECTOR<double>& meanRevK,
                                        const VECTOR<double>& mdec,
										const VECTOR<double>& Bounds,
										const VECTOR<double>& optimizerParams,
                                        long calibrate,
										ARM_result& result,
										long objId = -1);

extern long ARM_ARM_BootstCalibFRMModel(long zcId,
										long pf1Id,
										long pf2Id,
										long pf3Id,
										long liborTypeId,
										const VECTOR<double>& CalibParams,
										const VECTOR<double>& initCurve,
										const VECTOR<double>& mdec,
										double meanRev,
										long   nbfactor,
										long   nbrows,
										long   nbcolumns,
										const VECTOR<double>& correlmatrix,
										long  VolType,
										long calibrate,  
										ARM_result& result,
										long objId = -1);

#endif	// ARM_MOD_H

// EOF %M%