#ifndef ARM_LOCAL_SWAP_H
#define ARM_LOCAL_SWAP_H


class ARM_result;

extern long ARMLOCAL_LiborAssetSwapMargin (long modelId,
										   double startDate,
										   double endDate,
										   double fixedRate,
										   long fixReceiveOrPayId,
										   long fixDayCountId,
										   long fixFrequencyId,
										   long fixDecompFrequencyId,
										   long fixPayTimingId,
										   long fixIntRuleId,
										   long liborTypeId,
										   double spread,
										   long floatResetFreqId,
										   long floatPayFreqId,
										   long assetGap,
										   long vFlag,
										   double price,
										   const CCString& discountCCy,
										   double redemptionPrice,
										   double supplFee,
										   long solve,
										   char* id,
										   ARM_result& result);

extern long ARMLOCAL_LiborAssetSwapPrice (long modelId,
										  double startDate,
										  double endDate,
										  double fixedRate,
										  long fixReceiveOrPayId,
										  long fixDayCountId,
										  long fixFrequencyId,
										  long fixDecompFrequencyId,
										  long fixPayTimingId,
										  long fixIntRuleId,
										  long liborTypeId,
										  double spread,
										  long floatResetFreqId,
										  long floatPayFreqId,
										  long assetGap,
										  long vFlag,
										  double margin,
										  const CCString& discountCcy,
										  double redemptionPrice,
										  double supplFee,
										  long solve,
										  const CCString& id,
										  double minValue,
										  double maxValue,
										  ARM_result& result);

extern long ARMLOCAL_LIBORSWAP (double StartDate,
								double EndDate,
								long LiborType,
								long ReceiveOrPay,
								double FixedRate,
								long spreadType,
								double Spread,
								bool CcyIsObject,
								const CCString& CcyName,
								long fixedDayCountId,
								long floatingDayCountId,
								ARM_result& result,
								long objId = -1);

extern long ARMLOCAL_FIXEDLEG (double startDate,
							   double endDate,
							   long receiveOrPay,
							   long fixedRateType,
							   double fixedRate,
							   long dayCount,
							   long freq,
							   long decompFreq,
							   long payTiming,
							   long intRule,
							   long stubRule,
							   bool ccyIsObject,
							   const CCString& ccyName,
							   const CCString& payCalName,
							   long nxChange,
							   double refDate,
							   long adjStartDateId,
							   long rollDay ,
							   ARM_result& result,
							   long objId = -1);

extern long ARMLOCAL_SWAPLEG (long irIndex,
							  double startDate,
							  double endDate,
							  long receiveOrPay,
                              long spreadType,
							  double spread,
							  bool ccyIsObject,
							  const CCString& ccyName,
							  long dayCount,
							  long resetGap,
							  CCString resetCal,
							  CCString payCal,
							  long decompPricingFlag,
							  long nxChange,
							  long stubRuleId,
							  double refDate,
							  long adjStartDateId,
							  long rollDay,
							  ARM_result& result,
							  long objId = -1);


extern long ARMLOCAL_LIBORLEG (double startDate,
							   double endDate,
							   long liborType,
							   long receiveOrPay,
							   long spreadType,
                               double spread,
							   long resetFreq,
							   long payFreq,
							   long resetTiming,
							   long payTiming,
							   bool ccyIsObject,
							   const CCString& ccyName,
							   long intRuleId,
							   long resetGap,
							   CCString resetCal,
							   CCString payCal,
							   long decompPricingFlag,
							   long nxChange,
							   long stubRuleId,
							   double refDate,
							   long adjStartDateId,
							   int couponDayCount,
							   ARM_result& result,
							   long objId = -1
							  );

extern long ARMLOCAL_SWAP_PRICE_TO_RATE (long sId,
										 double Date,
										 double Price,
										 long modId,
										 ARM_result& result);

extern long ARMLOCAL_SWAP_RATE_TO_PRICE (long sId,
										 double date,
										 double rate,
										 long modId,
										 ARM_result& result);

extern long ARMLOCAL_SWAP (long swapLeg1,
						   long swapLeg2,
						   long minPay,			
						   VECTOR<double>& fixedRates, // if there are past fixings to take into account
						   ARM_result& result,
						   long objId = -1);


extern long ARMLOCAL_SwapFromExpiry (CCString& expiry,
									 CCString& tenor,
									 long liborType,
									 double fixedRate,
									 bool ccyIsObject,
									 const CCString& CcyName,
									 ARM_result& result,
									 long objId = -1);


extern long ARMLOCAL_GETSWAPLEGFROMSWAP( long swapId,
										 int legNumber,
										 ARM_result& result, 
										 long objId = -1);

extern long ARMLOCAL_CMSLEG (double startDate,
							 double endDate,
							 long cmsTypeId,
							 long receiveOrPay,
							 long spreadType,
							 double spread,
							 long yieldDecompFreq,
							 long swapLegDayCount,
							 long resetFreq,
							 long payFreq,
							 long resetGap,
							 long intRule,
							 bool ccyIsObject,
							 const CCString& ccyName,
							 long resetTiming,
							 long stubRule,
							 long adjStartDate,
							 ARM_result& result,
							 long objId = -1);

extern long ARMLOCAL_REVERSEFLOAT(double startDate,
								  double endDate,
								  double NotionalRatio,
								  long receiveOrPay,
								  long liborType,
								  const CCString& fltccy,
								  long fltSpreadsId,
								  long fltDayCount,
								  long fxCouponsId,
								  long extraCouponsId,
								  const CCString& reverseCcy,
								  long payFreq,
								  long reverseIndexId,
								  long fxDayCount,
								  double multiplier,
								  double couponFloor,
								  double stubDate,
								  ARM_result& result,
								  long objId = -1);

extern long ARMLOCAL_CORRIDORLEG(double startDate,
								 double endDate,
								 long receiveOrPay,
								 long payIndexId,
								 long payFreq,
								 long spreadType,
								 double spread,
								 long refIndexId,
								 long resetFreq,
								 long paidRateResetTiming,
								 long refRateResetTiming,
								 long stubRule,
								 long levelDownId,
								 long downSpec,
								 long levelUpId,
								 long upSpec,
								 bool ccyIsObject,
								 const CCString& ccyName,
								 long MCFreq,
								 long MCInterp,
								 long LDPricingMethod,
                                 long decompPricingFlag,
								 CCString resetCal,
								 CCString payCal,
                                 long refIndexResetGap,
								 ARM_result& result,
								 long objId = -1);


extern long ARMLOCAL_CORRIDORLEGWITHFIXINGS( const double& startDate,
											 const double& endDate,
											 const int&	payReceive,
											 const long& payIndexId,
											 const long& payFreq,
											 const double& spread,
											 const long& spreadId,
											 const long& refIndexId,
											 const long& resetFreq,
											 const long& paidRateResetTiming,
											 const long& refRateResetTiming,
											 const long& stubRule,
											 const double& levelDown,
											 const long& levelDownId,
											 const long& downSpec,
											 const double& levelUp,
											 const long& levelUpId,
											 const long& upSpec,
											 const long& ccyId,
											 const double& decompPricingFlag,
											 const double& refIndexResetGap,
											 const long& refPastFixings,
											 const long& payPastFixings,
											 ARM_result& result,
											 long objId = -1);

extern long ARMLOCAL_RESTRIKABLELEG(double startDate,
									 double endDate,
									 long receiveOrPay,
									 long payIndexId,
									 long spreadId,
									 double spreadValue,
									 long refIndexId,
									 long stubRule,
									 long rangeId,
									 double rangeValue,
									 bool ccyIsObject,
									 const CCString& ccyName,
									 double Alpha,
									 double Beta,
									 long decompPricingFlag,
									 long AdjStartDateFlag,
									 ARM_result& result,
									 long objId = -1);

extern long ARMLOCAL_CMTLEG (double startDate,
							 double endDate,
							 long cmtTypeId,
							 long bondCouponFreq,
							 long bondDayCount,
							 long receiveOrPay,
							 double spread,
							 long yieldDecompFreq,
							 long swapLegDayCount,
							 long intRule,
							 long resetGap,
							 long resetFreq,
							 double ntlAmount,
							 bool ccyIsObject,
							 const CCString& ccyName,
							 long resetTiming,
							 long adjStartDate,
							 ARM_result& result,
							 long objId = -1);

extern long ARMLOCAL_TMLEG(long tmIxType,
						   double startDate,
						   double endDate,
						   long receiveOrPay,
						   double spread,
                           int payfreq,
                           int resetFreq,
                           int intRule,
                           int fwdRule,
						   int stubRule,
                           bool ccyIsObject,
                           const CCString& ccyName,
						   ARM_result& result,
						   long objId = -1);


extern long ARMLOCAL_IMPLIEDSPREAD (long swapId,
									long modelId,
									double price,
									long leg1Or2,
									ARM_result& result);


extern long ARMLOCAL_ARM_GenAmortization (long swaplegId,
										  long amortMethodId,
										  long amortFrequency,
										  double amortAmount,
										  long daycountId,
										  double legNotional,
										  double amortRate,
										  double reducedMaturity,
										  long modelId,
										  double cleanup,
										  ARM_result& result,
										  long objId = -1);

extern long ARMLOCAL_SWAP_WITH_NOTIONNAL (long swapLeg1,
										  long swapLeg2,
										  long notId,
										  long minPay,
										  ARM_result& result,
										  long objId = -1);

extern long ARMLOCAL_ARM_CUSTOMFSTCPN (long swlegId,
									   double date,
									   ARM_result& result);

extern long ARMLOCAL_REVERSESTICKYLEG (double startDate,
									   double endDate,
									   long liborType,
									   long receiveOrPay,
									   long resetFreq,
									   long payFreq,
									   long resetTiming,
									   long payTiming,
									   bool ccyIsObject,
									   const CCString& ccyName,
									   long kRefValId,
									   long spreadRefValId,
									   double firstCoupon,
									   ARM_result& result,
									   long objId = -1);

extern long ARMLOCAL_IMPLIEDSPREADWITHMODELS (long swapId,
											  long modelId1,
											  long modelId2,
											  double price,
											  long leg1Or2,
											  ARM_result& result);

extern long ARMLOCAL_ARM_SetLastFixing(long securityId,
									   double rate,
									   double beforeLastFixing,
                                       double asof,
									   double resetDate,
									   ARM_result& result,
									   long objId = -1);

extern long ARMLOCAL_ARM_SetFixRates(long securityId,
									 VECTOR<double>& fixedRates,
									 ARM_result& result,
									 long objId = -1);

extern long ARMLOCAL_GENLEG (VECTOR<double> startDates,
							 VECTOR<double> endDates,
							 VECTOR<double> paymentDates,
							 VECTOR<double> resetDates,
							 VECTOR<double> intDays,
							 VECTOR<double> fwdorfixing,
							 long notionalId,
							 long indexId,
							 long receiveOrPayId,
							 long fixrateorspreadType,
							 double fixrateorspread,
							 bool ccyIsObject,
							 const CCString& ccyName,
							 long NxId,
							 int couponDayCount, 
							 ARM_result& result,
							 long objId = -1);

extern long ARMLOCAL_SWAPLEG (long irIndex,
							  double startDate,
							  double endDate,
							  long receiveOrPay,
                              long spreadType,
							  double spread,
							  bool ccyIsObject,
							  const CCString& ccyName,
							  long dayCount,
                              long resetTiming,
							  long resetGap,
                              long payTiming,
                              long payGap,
							  CCString resetCal,
							  CCString payCal,
							  long decompPricingFlag,
							  long nxChange,
							  long stubRuleId,
							  double refDate,
							  long adjStartDateId,
							  ARM_result& result,
							  long objId = -1);


extern long ARMLOCAL_LIVRETALEG (double startDate,
							   double endDate,
							   long liborType,
							   long receiveOrPay,
							   long spreadType,
                               double spread,
							   long resetFreq,
							   long payFreq,
							   long resetTiming,
							   long payTiming,
							   bool ccyIsObject,
							   const CCString& ccyName,
							   long intRuleId,
							   long resetGap,
							   CCString resetCal,
							   CCString payCal,
							   long decompPricingFlag,
							   long nxChange,
							   long stubRuleId,
							   double refDate,
							   long adjStartDateId,
							   long daycountId,
							   ARM_result& result,
							   long objId = -1);


extern long ARMLOCAL_AVERAGE_LIBOR_LEG (	long				irIndex,
											double				startDate,
											double				endDate,
											long				receiveOrPay,
											long				spreadType,
											double				spread,
											bool				ccyIsObject,
											const CCString&		ccyName,
											long				dayCount,
											CCString			payCal,
											long				decompPricingFlag,
											long				nxChange,
											long				stubRuleId,
											double				refDate,
											long				adjStartDateId,
											double				couru,
											ARM_result&			result,
											long				objId =-1);


long ARMLOCAL_SWAP_FROM_SWAPTION (long			swaptId,
								  long			NDIndex,
								  ARM_result&	result,
								  long			objId = -1);

                              
#endif	// ARM_LOCAL_SWAP_H

/*----End Of File ----*/
// EOF %M%