//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Sirius.rc
//
#define IDS_PROJNAME                    100
#define IDR_ZEROCURVE                   101
#define IDR_ZEROCURVES                  102
#define IDR_DIVIDENDSCHEDULE            106
#define IDR_DIVIDENDSCHEDULES           107
#define IDR_POSITION                    109
#define IDR_POSITIONS                   110
#define IDR_ASSET                       112
#define IDR_ASSETS                      113
#define IDR_PRODUCT                     116
#define IDR_PRODUCTS                    117
#define IDR_MARKETDATA                  122
#define IDR_MARKETDATACOLLECTION        123
#define IDR_MONTECARLO                  126
#define IDR_MONTECARLOCOLLECTION        127
#define IDD_DLGSETUP                    128
#define IDR_DEAL                        129
#define IDR_DEALS                       130
#define IDR_ARRAY                       131
#define IDR_ARRAYS                      132
#define IDR_DATE                        135
#define IDR_DATES                       136
#define IDR_INTERPOLATOR                137
#define IDR_INTERPOLATORS               138
#define IDR_STRIKES                     139
#define IDR_STRIKESCOLLECTION           140
#define IDR_VOLATILITYSTRUCTURE         143
#define IDR_VOLATILITYSTRUCTURES        144
#define IDR_RESULT                      145
#define IDR_RESULTS                     146
#define IDR_PARAMETERLIST               147
#define IDR_PARAMETERLISTS              148
#define IDR_VOLDATA                     149
#define IDR_VOLDATACOLLECTION           150
#define IDR_JUMPWINGVOLDATA             152
#define IDR_JUMPWINGVOLDATACOLLECTION   153
#define IDR_SVLVOLDATA                  154
#define IDR_SVLVOLDATACOLLECTION        155
#define IDR_SVLFITVOLDATA               156
#define IDR_SVLFITVOLDATACOLLECTION     157
#define IDR_HULLVOLDATA                 159
#define IDR_HULLVOLDATACOLLECTION       160
#define IDD_DLGINSERT                   161
#define IDR_SWAP                        166
#define IDD_DLGMODULESAVE               169
#define IDD_DLGMODULESAVELOAD           170
#define IDR_PARAMETER                   171
#define IDR_PARAMETERS                  172
#define IDR_SIRIUSAPPLICATION           173
#define IDR_DATESCHEDULE                174
#define IDR_DATESCHEDULES               175
#define IDR_SPOTSCHEDULE                176
#define IDR_SPOTSCHEDULES               177
#define IDR_CORRELATIONMATRIX           178
#define IDR_CORRELATIONMATRICES         179
#define IDR_RAMVOLDATA                  180
#define IDR_RAMVOLDATACOLLECTION        181
#define IDR_RAMFITVOLDATA               182
#define IDR_RAMFITVOLDATACOLLECTION     183
#define IDR_PROGRESS                    184
#define IDR_ARPROPVOLDATA               185
#define IDR_ARPROPVOLDATACOLLECTION     186
#define IDR_ARPROPFITVOLDATA            187
#define IDR_ARPROPFITVOLDATACOLLECTION  188
#define IDR_MULTIPLIERVOLDATA           189
#define IDR_MULTIPLIERVOLDATACOLLECTION 190
#define IDR_HULLANDWHITE                191
#define IDR_HULLANDWHITECOLLECTION      192
#define IDR_SETUP                       193
#define IDR_MATRIX                      195
#define IDR_MATRICES                    196
#define IDR_JUMPWINGFITVOLDATA          197
#define IDR_JUMPWINGFITVOLDATACOLLECTION 198
#define IDR_HERMITEVOLDATA              199
#define IDR_HERMITEVOLDATACOLLECTION    200
#define IDR_SCENARIO                    201
#define IDR_SCENARIOS                   202
#define IDR_RESULTSCOLLECTION           203
#define IDR_PDE                         204
#define IDR_PDECOLLECTION               205
#define IDI_SETUP                       206
#define IDC_RADIO_SQL                   207
#define IDC_RADIO_LOCAL                 208
#define IDR_IDR_VOLDATA1                208
#define IDC_EDIT_ROOT                   209
#define IDC_EDIT_USER                   210
#define IDC_EDIT_PRODUCT_TYPES          211
#define IDB_IMAGELIST                   211
#define IDC_BROWSE                      212
#define IDC_TXT_SAVE                    213
#define IDC_REFRESH                     214
#define IDC_EDIT_PASSWORD               214
#define IDC_PRODUCT_ONLY                215
#define IDI_ODBC                        215
#define IDC_BROWSE_ROOT                 215
#define IDC_TXT_DSN_BWL                 216
#define IDC_LIST                        217
#define IDC_EDIT_USER_BWL               217
#define IDC_TREE_MODULE                 218
#define IDC_EDIT_PASSWORD_BWL           218
#define IDC_EDIT_PREVIEW                219
#define IDC_EDIT_SPOT_SCHEDULE_SOURCE_BWL 219
#define IDC_EDIT_INTERPOLATION_BWL      220
#define IDC_DELETE                      221
#define IDC_COMBOBOXEX                  223
#define IDC_CHECK_PUBLISHING            224
#define IDC_TXT_USER                    225
#define IDC_TXT_PASSWORD                226
#define IDC_COMBO_DSN                   227
#define IDC_USE_BWL                     228
#define IDC_BOUNCE_DATABASES            229
#define IDC_COMBO_DATABASE_MODE         230
#define IDC_YESTERDAY_CLOSE             231
#define IDC_DISPAY_SIRIUS_STATUS        232
#define IDC_COMBO_LOCATION              233
#define IDC_COMBO_DATASOURCE            234
#define IDC_DISPLAY_FUNCTIONS           235
#define IDC_SAVE                        236
#define IDC_REVERT                      237
#define IDC_TAB                         238
#define IDC_TXT_PRODUCT_TYPES           239
#define IDC_TXT_DATABASE                240
#define IDC_TXT_DATASOURCE              241
#define IDC_TXT_LOCATION                242
#define IDC_ICON_SETUP                  243
#define IDC_ICON_32                     244
#define IDC_COMBO_DSN_BWL               245
#define IDC_MODULE_NAME                 245
#define IDC_TXT_USER_BWL                246
#define IDC_PREVIEW                     246
#define IDC_TXT_PASSWORD_BWL            247
#define IDC_DOWNLOAD_TO                 247
#define IDC_TXT_SPOT_SCHEDULE_SOURCE_BWL 248
#define IDC_TXT_INTERPOLATION_BWL       249
#define IDC_FIRST_TRY                   250
#define IDC_COMBO_LOCATION_TRY          251
#define IDC_TXT_LOCATION_TRY            252
#define IDS_DISABLED_IN_WIZARD          0x0201
#define IDS_EVALUATE_FAILED             0x0202
#define IDS_POSITION_ID_INVALID         0x0203
#define IDS_HANDLE_IS_MISSING           0x0204
#define IDS_BOOK_ID_INVALID             0x0205
#define IDS_INVALID_PATH                0x0206
#define IDS_INVALID_FILE                0x0207
#define IDS_INVALID_PARAMETER           0x0208
#define IDS_INVALID_HANDLE_PARAMETER    0x0209
#define IDS_EVALUATE_VALUE              0x020A
#define IDS_INITIALISE_MONTE_CARLO_EXCEPTION 0x020B
#define IDS_ARRAY_INDEX                 0x020C
#define IDS_NO_OBJECT_WITH_HANDLE       0x020D
#define IDS_PARAMETER_NOT_USED          0x020E
#define IDS_INTERPOLATOR_TYPE           0x020F
#define IDS_NUMBER_PARAMETERS           0x0210
#define IDS_STRIKE_TYPE                 0x0211
#define IDS_ROWS_INVALID                0x0212
#define IDS_COLUMNS_INVALID             0x0213
#define IDS_DATA_ELEMENT_NOT_FOUND      0x0214
#define IDS_CREATE_OBJECT               0x0215
#define IDS_INVALID_DATE                0x0216
#define IDS_INVALID_DISCOUNT_FACTOR     0x0217
#define IDS_INVALID_FORWARD             0x0218
#define IDS_INVALID_NAME                0x0219
#define IDS_NO_HANDLE_OF_TYPE           0x021A
#define IDS_TERM_FORWARD_VOLATILITY_INVALID 0x021B
#define IDS_HANDLE_ALREADY_IN_USE       0x021D
#define IDS_NAME_ALREADY_IN_USE         0x021E
#define IDS_INVALID_INTERPOLATOR_TYPE   0x021F
#define IDS_INVALID_VOLATILITY_DATA_TYPE 0x0220
#define IDS_VOLATILITY_DATA_MUST_BE_BLANK 0x0221
#define IDS_INVALID_SPOT                0x0222
#define IDS_UNHANDLED_VOLATLITY_DATA_TYPE 0x0223
#define IDS_UNHANDLED_EXCEPTION         0x0224
#define IDS_INVALID_VOLAILITY_DATA      0x0225
#define IDS_INVALID_BIDASKMID_ENUM      0x0226
#define IDS_NO_DATA_FOUND               0x0227
#define IDS_INVALID_Y_DATA              0x0228
#define IDS_VALID_ONLY_IN_EXCEL         0x0229
#define IDS_INVALID_VOLATILITY_DATA_HANDLE 0x022A
#define IDS_DEAL_ID_INVALID             0x022B
#define IDS_INVALID_CALENDAR            0x022C
#define IDS_INVALID_DAY_COUNT_CONVENTION 0x022D
#define IDS_INVALID_BUSINESS_DAY_CONVENTION 0x022E
#define IDS_VALUE_PROPERTY_NOT_FOUND    0x022F
#define IDS_PROPERTY_NOT_FOUND          0x0230
#define IDS_RATE_COMPONENT_TYPE         0x0231
#define IDS_HEADER_STRIKE               0x0500
#define IDS_HEADER_INTERPOLATOR         0x0501
#define IDS_HEADER_VOLATILITY_DATA      0x0502
#define IDS_HEADER_PRICE                0x0504
#define IDS_HEADER_THETA                0x0505
#define IDS_HEADER_RETURN_HANDLE_OPT    0x0506
#define IDS_INVALID_PARAMETER_VALUE     0x0507
#define IDS_HEADER_NAME                 0x0508
#define IDS_HEADER_VALUE                0x0509
#define IDS_HEADER_PARAMETER_LIST       0x050A
#define IDS_HEADER_DATES                0x050B
#define IDS_HEADER_PRODUCT_TYPE         0x050C
#define IDS_HEADER_DIVIDEND_SCHEDULE    0x050D
#define IDS_HEADER_VOLATILITY_STRUCTURE 0x050E
#define IDS_HEADER_SPOT                 0x050F
#define IDS_HEADER_ZERO_CURVE           0x0510
#define IDS_HEADER_BOOK                 0x0511
#define IDS_HEADER_COUNTERPARTY         0x0512
#define IDS_HEADER_DESCRIPTION          0x0513
#define IDS_HEADER_NOTIONAL             0x0514
#define IDS_HEADER_IDENTIFIER           0x0515
#define IDS_HEADER_PRODUCT              0x0516
#define IDS_HEADER_POSITION             0x0517
#define IDS_HEADER_FREQUENCY            0x0518
#define IDS_HEADER_START_DATE           0x0519
#define IDS_HEADER_END_DATE             0x0520
#define IDS_HEADER_DAY_COUNT_CONVENTION 0x0521
#define IDS_HEADER_DATE                 0x0522
#define IDS_HEADER_POSITION_LIST        0x0523
#define IDS_HEADER_SETTLEMENT_DAYS      0x0524
#define IDS_HEADER_QUOTES               0x0525
#define IDS_KEY_NOT_FOUND               0x0526
#define IDS_INVALID_X_VALUE             0x0527
#define IDS_NO_MODULE_SELECTED          0x0528
#define IDS_NO_MODULES_FOUND            0x0529
#define IDS_INVALID_DSN                 0x0530
#define IDS_NO_WORKBOOKS_FOUND          0x0531
#define IDS_NO_WORKBOOK_SELECTED        0x0532
#define IDS_DELETE_CONFIRM              0x0533
#define IDS_INVALID_VALUE_FOR_PARAMETER 0x0544
#define IDS_EVALUATE_NOT_FOUND          0x0545
#define IDS_PRODUCTS_ARRAY_INVALID      0x0546
#define IDS_CANNOT_PROCESS_OBJECT       0x0547
#define IDS_NEITHER_FRA_BLANK           0x0548
#define IDS_DLL_NOT_REGISTERED          0x0549
#define IDS_MSG_INVALID_ENUMERATOR      0x0550
#define IDS_MSG_INVALID_PARAMETER       0x0551
#define IDS_VECTOR_NAMES_INVALID        0x0552
#define IDS_VECTOR_VALUES_INVALID       0x0553
#define IDS_INVALID_PRODUCT_TYPE        0x0554
#define IDS_VALUE_NOT_USED              0x0555
#define IDS_PUBLISHING_NOT_ENABLED      0x0556
#define IDS_INVALID_MATURITY            0x0557
#define IDS_INVALID_STRIKES             0x0558
#define IDS_INVALID_SHIFTS              0x0559
#define IDS_INVALID_PRODUCT_TYPE_FILE   0x055A
#define IDS_VECTOR_DATES_INVALID        0x055B
#define IDS_DUPLICATE_DATE_IN_SCHEDULE  0x055C
#define IDS_MSG_NOT_NUMERIC_AT_DATE     0x055D
#define IDS_NO_VALUE_AT_DATE            0x055E
#define IDS_SCHEDULE_EMPTY              0x055F
#define IDS_INVALID_ZERO_CURVE_TYPE     0x0560
#define IDS_INVALID_CURRENCY            0x0561
#define IDS_FIND_OBJECT                 0x0562
#define IDS_INVALID_OBJECT_NAME         0x0563
#define IDS_COULD_NOT_GET_VALUE         0x0564
#define IDS_CHANGE_OF_VARIABLE_FAILED   0x0565
#define IDS_UNHANDLED_DATA_TYPE         0x0566
#define IDS_LOAD_OBJECT                 0x0567
#define IDS_INVALID_IDENTIFIER          0x0568
#define IDS_INTERNAL_HANDLE_FAIL        0x0569
#define IDS_HEADER_POSITION_NOTIONAL_LIST 0x056A
#define IDS_DUPLICATE_CORRELATION       0x056B
#define IDS_COULD_NOT_PARSE_XML         0x056C
#define IDS_XML_NOT_OBJECT              0x056D
#define IDS_XML_UNEXPECTED_END          0x056E
#define IDS_INCONSISTENT_DCC            0x056F
#define IDS_SAVE_NOT_FOUND              0x0570
#define IDS_SPOT_SCHEDULE_EMPTY         0x0571
#define IDS_NOT_NUMBER_AT_DATE          0x0572
#define IDS_NO_SPOT_SCHEDULE_IN_ASSET   0x0573
#define IDS_CANNOT_FIND_ASSET           0x0574
#define IDS_NO_NUMERIC_DATA_FOUND       0x0575
#define IDS_CANNOT_FIND_ZEROCURVE       0x0576
#define IDS_CANNOT_FIND_PARAMETER       0x0577
#define IDS_ASSET_NAME_INVALID          0x0578
#define IDS_VECTOR_SIZES_DIFFER         0x0579
#define IDS_CANNOT_SAVE_SPOT            0x057A
#define IDS_CANNOT_FIND_DIVIDENDSCHEDULE 0x057B
#define IDS_CANNOT_FIND_VOLATILITYSTRUCTURE 0x057C
#define IDS_TOO_MANY_COLUMNS            0x057D
#define IDS_INVALID_INTERVAL_PARAMETER  0x057E
#define IDS_CANNOT_SAVE_USD_SPOT        0x057F
#define IDS_NOT_MARKET_DATA_OBJECT      0x0580
#define IDS_OBJECT_BOUNDARY             0x0581
#define IDS_MARKET_DATA_ROOT_ERROR      0x0582
#define IDS_MONTE_CARLO_TYPE            0x0583
#define IDS_HEADER_PAYCURRENCYASSET     0x0584
#define IDS_HEADER_COMPOSITECURRENCYASSET 0x0585
#define IDS_HEADER_DIVISOR              0x0586
#define IDS_CANNOT_SAVE_OBJECT          0x0587
#define IDS_ASSET_SAVE_INVALID          0x0588
#define IDS_ASSET_NO_NAME               0x0589
#define IDS_PUT_VALUE_RESULT            0x058A
#define IDS_XML_WHITESPACE              0x058B
#define IDS_LOAD_NOT_ENABLED            0x058C
#define IDS_INVALID_WEIGHTS             0x058D
#define IDS_DUPLICATE_POSITION_ID       0x058E
#define IDS_TOO_MANY_POSITIONS_IN_DEAL  0x058F
#define IDS_CANNOT_NULLIFY_MARKET_DATA  0x0590
#define IDS_HEADER_DATA_SOURCE          0x0592
#define IDS_HEADER_DATE_LIST            0x0593

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32769
#define _APS_NEXT_CONTROL_VALUE         248
#define _APS_NEXT_SYMED_VALUE           206
#endif
#endif
