/////////////////////////////////////////////////////////////////////////////
// Name:        ito33/prologue.h
// Purpose:     header to be included in the beginning of all public headers
// Author:      Vadim Zeitlin
// Created:     2005-09-29
// RCS-ID:      $Id: prologue.h,v 1.2 2005/10/03 12:40:10 zeitlin Exp $
// Copyright:   (c) 2005 Trilemma LLP
/////////////////////////////////////////////////////////////////////////////

/**
    @file ito33/prologue.h
    @brief Header to be included in the very beginning of all the public
    headers.

    This file contains pragmas which affect all the headers following until the
    inclusion of ito33/epilogue.h. There should always be a matching inclusion
    of the latter header for each inclusion of this one.
 */

#ifndef _ITO33_PROLOGUE_H_
#define _ITO33_PROLOGUE_H_

#ifdef _MSC_VER
  // set the same packing as used by ITO33 internally
  #pragma pack(push, 8)

  // and suppress the warning generated by changing alignment in the header:
  // bad as it is to disable warnings in the headers, we simply have to do it
  // for this one, there is no way to avoid it otherwise
  #pragma warning(disable: 4103)
#endif // _MSC_VER

#endif // _ITO33_PROLOGUE_H_

