// This file is automatically generated from RadarLib.cpp (which see for more info)
// Do not edit it: your changes will be overwritten.
// Do not add it to the Subversion repository.





























#include "edginc/config.hpp"
#include "edginc/RadarLib.hpp"
#include "edginc/ModelException.hpp"

DRLIB_BEGIN_NAMESPACE
extern bool RadarRepWrapperLoad();
extern bool RadarRepAddinLoad();
extern bool PolyBasisWrapperLoad();
extern bool IFuncBasisWrapperLoad();
extern bool IFittingVarTransWrapperLoad();
extern bool IdentityTransWrapperLoad();

void RadarLib::linkInClasses(){
    /* The sole purpose of this method is to ensure that the linker 
       includes all symbols out of the market directory. Many symbols
       are automatically linked because they are used by other classes
       which are already included.

       An example of symbols that could be dropped would be an entire class
       representing a product. For example Vanilla might be dropped since
       the only references might be throught the abstract parent class. */


    /* there is no order dependency - this could be automated */

    // Please don't add any new ...::TYPE entries here ---

    bool success =
		PolyBasisWrapperLoad() &&
		IFuncBasisWrapperLoad() &&
        IFittingVarTransWrapperLoad() &&
        IdentityTransWrapperLoad() &&
		RadarRepWrapperLoad() &&
		RadarRepAddinLoad() &&
        true;

    if (!success){
        throw ModelException("RadarLib::registerClasses",
                             "Registration error");
    }
}

DRLIB_END_NAMESPACE