#ifndef NAG_NAMES
#define NAG_NAMES  

/* <nag_names.h>
 *
 * Copyright 1990 Numerical Algorithms Group
 *
 * Maps longer meaningful names to NAG names.
 *
 * Mark 1, 1990.
 * Mark 1a revised. IER-863 (Oct 1990).
 * Mark 2 revised.
 * Mark 2a revised. IER-968 (Jun 1992).
 * Mark 4 revised. IER-1756 (Aug 1995).
 * Mark 5 revised. IER-2136 (Feb 1998).
 */

#define  nag_implementation_details          a00aac  /* Mark 1 */ 
#define  nag_complex                         a02bac  /* Mark 2 */ 
#define  nag_complex_real                    a02bbc  /* Mark 2 */ 
#define  nag_complex_imag                    a02bcc  /* Mark 2 */ 
#define  nag_complex_add                     a02cac  /* Mark 2 */ 
#define  nag_complex_subtract                a02cbc  /* Mark 2 */ 
#define  nag_complex_multiply                a02ccc  /* Mark 2 */ 
#define  nag_complex_divide                  a02cdc  /* Mark 2 */ 
#define  nag_complex_negate                  a02cec  /* Mark 2 */ 
#define  nag_complex_conjg                   a02cfc  /* Mark 2 */ 
#define  nag_complex_equal                   a02cgc  /* Mark 2 */ 
#define  nag_complex_not_equal               a02chc  /* Mark 2 */ 
#define  nag_complex_arg                     a02dac  /* Mark 2 */ 
#define  nag_complex_abs                     a02dbc  /* Mark 2 */ 
#define  nag_complex_sqrt                    a02dcc  /* Mark 2 */ 
#define  nag_complex_i_power                 a02ddc  /* Mark 2 */ 
#define  nag_complex_r_power                 a02dec  /* Mark 2 */ 
#define  nag_complex_c_power                 a02dfc  /* Mark 2 */ 
#define  nag_complex_log                     a02dgc  /* Mark 2 */ 
#define  nag_complex_exp                     a02dhc  /* Mark 2 */ 
#define  nag_complex_sin                     a02djc  /* Mark 2 */ 
#define  nag_complex_cos                     a02dkc  /* Mark 2 */ 
#define  nag_complex_tan                     a02dlc  /* Mark 2 */ 
#define  nag_zeros_complex_poly              c02afc  /* Mark 2 */ 
#define  nag_zeros_real_poly                 c02agc  /* Mark 2 */ 
#define  nag_zero_cont_func_bd               c05adc  /* Mark 2 */ 
#define  nag_zero_nonlin_eqns                c05nbc  /* Mark 2 */ 
#define  nag_zero_nonlin_eqns_deriv          c05pbc  /* Mark 2 */ 
#define  nag_zero_cont_func_bd_1             c05sdc  /* Mark 5 */ 
#define  nag_zero_nonlin_eqns_1              c05tbc  /* Mark 5 */ 
#define  nag_zero_nonlin_eqns_deriv_1        c05ubc  /* Mark 5 */ 
#define  nag_check_deriv                     c05zbc  /* Mark 2 */ 
#define  nag_check_deriv_1                   c05zcc  /* Mark 5 */ 
#define  nag_fft_real                        c06eac  /* Mark 1 */ 
#define  nag_fft_hermitian                   c06ebc  /* Mark 1 */ 
#define  nag_fft_complex                     c06ecc  /* Mark 1 */ 
#define  nag_convolution_real                c06ekc  /* Mark 1 */ 
#define  nag_fft_multiple_real               c06fpc  /* Mark 1 */ 
#define  nag_fft_multiple_hermitian          c06fqc  /* Mark 1 */ 
#define  nag_fft_multiple_complex            c06frc  /* Mark 1 */ 
#define  nag_fft_2d_complex                  c06fuc  /* Mark 1 */ 
#define  nag_conjugate_hermitian             c06gbc  /* Mark 1 */ 
#define  nag_conjugate_complex               c06gcc  /* Mark 1 */ 
#define  nag_multiple_conjugate_hermitian    c06gqc  /* Mark 1 */ 
#define  nag_multiple_hermitian_to_complex   c06gsc  /* Mark 1 */ 
#define  nag_fft_init_trig                   c06gzc  /* Mark 1 */ 
#define  nag_fft_multiple_sine               c06hac  /* Mark 2 */ 
#define  nag_fft_multiple_cosine             c06hbc  /* Mark 2 */ 
#define  nag_fft_multiple_qtr_sine           c06hcc  /* Mark 2 */ 
#define  nag_fft_multiple_qtr_cosine         c06hdc  /* Mark 2 */ 
#define  nag_1d_quad_gen                     d01ajc  /* Mark 2 */ 
#define  nag_1d_quad_osc                     d01akc  /* Mark 2 */ 
#define  nag_1d_quad_brkpts                  d01alc  /* Mark 2 */ 
#define  nag_1d_quad_inf                     d01amc  /* Mark 2 */ 
#define  nag_1d_quad_wt_trig                 d01anc  /* Mark 2 */ 
#define  nag_1d_quad_wt_alglog               d01apc  /* Mark 2 */ 
#define  nag_1d_quad_wt_cauchy               d01aqc  /* Mark 2 */ 
#define  nag_1d_quad_inf_wt_trig             d01asc  /* Mark 2 */ 
#define  nag_1d_quad_gauss                   d01bac  /* Mark 2 */ 
#define  nag_multid_quad_adapt               d01fcc  /* Mark 2 */ 
#define  nag_1d_quad_vals                    d01gac  /* Mark 2 */ 
#define  nag_multid_quad_monte_carlo         d01gbc  /* Mark 2 */ 
#define  nag_1d_quad_gen_1                   d01sjc  /* Mark 5 */ 
#define  nag_1d_quad_osc_1                   d01skc  /* Mark 5 */ 
#define  nag_1d_quad_brkpts_1                d01slc  /* Mark 5 */ 
#define  nag_1d_quad_inf_1                   d01smc  /* Mark 5 */ 
#define  nag_1d_quad_wt_trig_1               d01snc  /* Mark 5 */ 
#define  nag_1d_quad_wt_alglog_1             d01spc  /* Mark 5 */ 
#define  nag_1d_quad_wt_cauchy_1             d01sqc  /* Mark 5 */ 
#define  nag_1d_quad_inf_wt_trig_1           d01ssc  /* Mark 5 */ 
#define  nag_1d_quad_gauss_1                 d01tac  /* Mark 5 */ 
#define  nag_multid_quad_adapt_1             d01wcc  /* Mark 5 */ 
#define  nag_multid_quad_monte_carlo_1       d01xbc  /* Mark 5 */ 
#define  nag_ode_ivp_adams_gen               d02cjc  /* Mark 2 */ 
#define  nag_ode_ivp_bdf_gen                 d02ejc  /* Mark 3 */ 
#define  nag_ode_bvp_fd_nonlin_fixedbc       d02gac  /* Mark 3 */ 
#define  nag_ode_bvp_fd_lin_gen              d02gbc  /* Mark 3 */ 
#define  nag_ode_ivp_rk_range                d02pcc  /* Mark 3 */ 
#define  nag_ode_ivp_rk_onestep              d02pdc  /* Mark 3 */ 
#define  nag_ode_ivp_rk_free                 d02ppc  /* Mark 3 */ 
#define  nag_ode_ivp_rk_setup                d02pvc  /* Mark 3 */ 
#define  nag_ode_ivp_rk_reset_tend           d02pwc  /* Mark 3 */ 
#define  nag_ode_ivp_rk_interp               d02pxc  /* Mark 3 */ 
#define  nag_ode_ivp_rk_errass               d02pzc  /* Mark 3 */ 
#define  nag_ode_ivp_adams_roots             d02qfc  /* Mark 2 */ 
#define  nag_ode_ivp_adams_setup             d02qwc  /* Mark 2 */ 
#define  nag_ode_ivp_adams_free              d02qyc  /* Mark 2 */ 
#define  nag_ode_ivp_adams_interp            d02qzc  /* Mark 2 */ 
#define  nag_ode_bvp_fd_nonlin_gen           d02rac  /* Mark 3 */ 
#define  nag_1d_spline_interpolant           e01bac  /* Mark 2 */ 
#define  nag_monotonic_interpolant           e01bec  /* Mark 1 */ 
#define  nag_monotonic_evaluate              e01bfc  /* Mark 2 */ 
#define  nag_monotonic_deriv                 e01bgc  /* Mark 2 */ 
#define  nag_monotonic_intg                  e01bhc  /* Mark 2 */ 
#define  nag_2d_spline_interpolant           e01dac  /* Mark 2 */ 
#define  nag_2d_scat_interpolant             e01sac  /* Mark 3 */ 
#define  nag_2d_scat_eval                    e01sbc  /* Mark 3 */ 
#define  nag_2d_scat_free                    e01szc  /* Mark 3 */ 
#define  nag_1d_cheb_fit                     e02adc  /* Mark 5 */ 
#define  nag_1d_cheb_eval                    e02aec  /* Mark 5 */ 
#define  nag_1d_cheb_interp_fit              e02afc  /* Mark 5 */ 
#define  nag_1d_spline_fit_knots             e02bac  /* Mark 2 */ 
#define  nag_1d_spline_evaluate              e02bbc  /* Mark 2 */ 
#define  nag_1d_spline_deriv                 e02bcc  /* Mark 2 */ 
#define  nag_1d_spline_intg                  e02bdc  /* Mark 2 */ 
#define  nag_1d_spline_fit                   e02bec  /* Mark 2 */ 
#define  nag_2d_spline_fit_grid              e02dcc  /* Mark 2 */ 
#define  nag_2d_spline_fit_scat              e02ddc  /* Mark 2 */ 
#define  nag_2d_spline_eval                  e02dec  /* Mark 2 */ 
#define  nag_2d_spline_eval_rect             e02dfc  /* Mark 2 */ 
#define  nag_opt_one_var_no_deriv            e04abc  /* Mark 5 */ 
#define  nag_opt_one_var_deriv               e04bbc  /* Mark 5 */ 
#define  nag_opt_simplex                     e04ccc  /* Mark 4 */ 
#define  nag_opt_conj_grad                   e04dgc  /* Mark 2 */ 
#define  nag_opt_lsq_no_deriv                e04fcc  /* Mark 2 */ 
#define  nag_opt_lsq_deriv                   e04gbc  /* Mark 2 */ 
#define  nag_opt_check_deriv                 e04hcc  /* Mark 2 */ 
#define  nag_opt_check_2nd_deriv             e04hdc  /* Mark 5 */ 
#define  nag_opt_bounds_no_deriv             e04jbc  /* Mark 2 */ 
#define  nag_opt_bounds_deriv                e04kbc  /* Mark 2 */ 
#define  nag_opt_bounds_2nd_deriv            e04lbc  /* Mark 5 */ 
#define  nag_opt_lp                          e04mfc  /* Mark 2 */ 
#define  nag_opt_sparse_mps_free             e04myc  /* Mark 5 */ 
#define  nag_opt_sparse_mps_read             e04mzc  /* Mark 5 */ 
#define  nag_opt_lin_lsq                     e04ncc  /* Mark 5 */ 
#define  nag_opt_qp                          e04nfc  /* Mark 2 */ 
#define  nag_opt_sparse_convex_qp            e04nkc  /* Mark 5 */ 
#define  nag_opt_nlp                         e04ucc  /* Mark 4 */ 
#define  nag_opt_nlin_lsq                    e04unc  /* Mark 5 */ 
#define  nag_opt_estimate_deriv              e04xac  /* Mark 5 */ 
#define  nag_opt_init                        e04xxc  /* Mark 2 */ 
#define  nag_opt_read                        e04xyc  /* Mark 2 */ 
#define  nag_opt_free                        e04xzc  /* Mark 2 */ 
#define  nag_opt_lsq_check_deriv             e04yac  /* Mark 2 */ 
#define  nag_opt_lsq_covariance              e04ycc  /* Mark 2 */ 
#define  nag_complex_cholesky                f01bnc  /* Mark 1 */ 
#define  nag_real_cholesky_skyline           f01mcc  /* Mark 1 */ 
#define  nag_real_qr                         f01qcc  /* Mark 1 */ 
#define  nag_real_apply_q                    f01qdc  /* Mark 1 */ 
#define  nag_real_form_q                     f01qec  /* Mark 1 */ 
#define  nag_complex_qr                      f01rcc  /* Mark 1 */ 
#define  nag_complex_apply_q                 f01rdc  /* Mark 1 */ 
#define  nag_complex_form_q                  f01rec  /* Mark 1 */ 
#define  nag_real_symm_eigenvalues           f02aac  /* Mark 2 */ 
#define  nag_real_symm_eigensystem           f02abc  /* Mark 2 */ 
#define  nag_real_symm_general_eigenvalues   f02adc  /* Mark 2 */ 
#define  nag_real_symm_general_eigensystem   f02aec  /* Mark 2 */ 
#define  nag_real_eigenvalues                f02afc  /* Mark 2 */ 
#define  nag_real_eigensystem                f02agc  /* Mark 1 */ 
#define  nag_hermitian_eigenvalues           f02awc  /* Mark 2 */ 
#define  nag_hermitian_eigensystem           f02axc  /* Mark 2 */ 
#define  nag_real_general_eigensystem        f02bjc  /* Mark 2 */ 
#define  nag_real_eigensystem_sel            f02ecc  /* Mark 5 */ 
#define  nag_complex_eigensystem_sel         f02gcc  /* Mark 5 */ 
#define  nag_real_svd                        f02wec  /* Mark 1 */ 
#define  nag_complex_svd                     f02xec  /* Mark 1 */ 
#define  nag_real_cholesky                   f03aec  /* Mark 1 */ 
#define  nag_real_lu                         f03afc  /* Mark 1 */ 
#define  nag_complex_lu                      f03ahc  /* Mark 1 */ 
#define  nag_complex_lin_eqn_mult_rhs        f04adc  /* Mark 1 */ 
#define  nag_real_cholesky_solve_mult_rhs    f04agc  /* Mark 1 */ 
#define  nag_real_lu_solve_mult_rhs          f04ajc  /* Mark 1 */ 
#define  nag_complex_lu_solve_mult_rhs       f04akc  /* Mark 1 */ 
#define  nag_real_lin_eqn                    f04arc  /* Mark 1 */ 
#define  nag_hermitian_lin_eqn_mult_rhs      f04awc  /* Mark 1 */ 
#define  nag_real_cholesky_skyline_solve     f04mcc  /* Mark 1 */ 
#define  dgemv                               f06pac  /* Mark 1 */ 
#define  dgbmv                               f06pbc  /* Mark 1 */ 
#define  dsymv                               f06pcc  /* Mark 1 */ 
#define  dsbmv                               f06pdc  /* Mark 1 */ 
#define  dspmv                               f06pec  /* Mark 1 */ 
#define  dtrmv                               f06pfc  /* Mark 1 */ 
#define  dtbmv                               f06pgc  /* Mark 1 */ 
#define  dtpmv                               f06phc  /* Mark 1 */ 
#define  dtrsv                               f06pjc  /* Mark 1 */ 
#define  dtbsv                               f06pkc  /* Mark 1 */ 
#define  dtpsv                               f06plc  /* Mark 1 */ 
#define  dger                                f06pmc  /* Mark 1 */ 
#define  dsyr                                f06ppc  /* Mark 1 */ 
#define  dspr                                f06pqc  /* Mark 1 */ 
#define  dsyr2                               f06prc  /* Mark 1 */ 
#define  dspr2                               f06psc  /* Mark 1 */ 
#define  zgemv                               f06sac  /* Mark 1 */ 
#define  zgbmv                               f06sbc  /* Mark 1 */ 
#define  zhemv                               f06scc  /* Mark 1 */ 
#define  zhbmv                               f06sdc  /* Mark 1 */ 
#define  zhpmv                               f06sec  /* Mark 1 */ 
#define  ztrmv                               f06sfc  /* Mark 1 */ 
#define  ztbmv                               f06sgc  /* Mark 1 */ 
#define  ztpmv                               f06shc  /* Mark 1 */ 
#define  ztrsv                               f06sjc  /* Mark 1 */ 
#define  ztbsv                               f06skc  /* Mark 1 */ 
#define  ztpsv                               f06slc  /* Mark 1 */ 
#define  zgeru                               f06smc  /* Mark 1 */ 
#define  zgerc                               f06snc  /* Mark 1 */ 
#define  zher                                f06spc  /* Mark 1 */ 
#define  zhpr                                f06sqc  /* Mark 1 */ 
#define  zher2                               f06src  /* Mark 1 */ 
#define  zhpr2                               f06ssc  /* Mark 1 */ 
#define  dgemm                               f06yac  /* Mark 1 */ 
#define  dsymm                               f06ycc  /* Mark 1 */ 
#define  dtrmm                               f06yfc  /* Mark 1 */ 
#define  dtrsm                               f06yjc  /* Mark 1 */ 
#define  dsyrk                               f06ypc  /* Mark 1 */ 
#define  dsyr2k                              f06yrc  /* Mark 1 */ 
#define  zgemm                               f06zac  /* Mark 1 */ 
#define  zhemm                               f06zcc  /* Mark 1 */ 
#define  ztrmm                               f06zfc  /* Mark 1 */ 
#define  ztrsm                               f06zjc  /* Mark 1 */ 
#define  zherk                               f06zpc  /* Mark 1 */ 
#define  zher2k                              f06zrc  /* Mark 1 */ 
#define  zsymm                               f06ztc  /* Mark 1 */ 
#define  zsyrk                               f06zuc  /* Mark 1 */ 
#define  zsyr2k                              f06zwc  /* Mark 1 */ 
#define  nag_sparse_nsym_fac                 f11dac  /* Mark 5 */ 
#define  nag_sparse_nsym_fac_sol             f11dcc  /* Mark 5 */ 
#define  nag_sparse_nsym_sol                 f11dec  /* Mark 5 */ 
#define  nag_sparse_sym_chol_fac             f11jac  /* Mark 5 */ 
#define  nag_sparse_sym_chol_sol             f11jcc  /* Mark 5 */ 
#define  nag_sparse_sym_sol                  f11jec  /* Mark 5 */ 
#define  nag_sparse_nsym_sort                f11zac  /* Mark 5 */ 
#define  nag_sparse_sym_sort                 f11zbc  /* Mark 5 */ 
#define  nag_summary_stats_1var              g01aac  /* Mark 1 */ 
#define  nag_5pt_summary_stats               g01alc  /* Mark 4 */ 
#define  nag_binomial_dist                   g01bjc  /* Mark 4 */ 
#define  nag_poisson_dist                    g01bkc  /* Mark 4 */ 
#define  nag_hypergeom_dist                  g01blc  /* Mark 4 */ 
#define  nag_deviates_normal_dist            g01cec  /* Mark 1 */ 
#define  nag_shapiro_wilk_test               g01ddc  /* Mark 4 */ 
#define  nag_ranks_and_scores                g01dhc  /* Mark 4 */ 
#define  nag_prob_normal                     g01eac  /* Mark 4 */ 
#define  nag_prob_students_t                 g01ebc  /* Mark 1 */ 
#define  nag_prob_chi_sq                     g01ecc  /* Mark 1 */ 
#define  nag_prob_f_dist                     g01edc  /* Mark 1 */ 
#define  nag_prob_beta_dist                  g01eec  /* Mark 1 */ 
#define  nag_gamma_dist                      g01efc  /* Mark 1 */ 
#define  nag_deviates_normal                 g01fac  /* Mark 4 */ 
#define  nag_deviates_students_t             g01fbc  /* Mark 1 */ 
#define  nag_deviates_chi_sq                 g01fcc  /* Mark 1 */ 
#define  nag_deviates_f_dist                 g01fdc  /* Mark 1 */ 
#define  nag_deviates_beta                   g01fec  /* Mark 1 */ 
#define  nag_deviates_gamma_dist             g01ffc  /* Mark 1 */ 
#define  nag_bivariate_normal_dist           g01hac  /* Mark 1 */ 
#define  nag_ken_spe_corr_coeff              g02brc  /* Mark 3 */ 
#define  nag_corr_cov                        g02bxc  /* Mark 3 */ 
#define  nag_simple_linear_regression        g02cac  /* Mark 3 */ 
#define  nag_regress_confid_interval         g02cbc  /* Mark 3 */ 
#define  nag_regsn_mult_linear               g02dac  /* Mark 1 */ 
#define  nag_regsn_mult_linear_addrem_obs    g02dcc  /* Mark 2 */ 
#define  nag_regsn_mult_linear_upd_model     g02ddc  /* Mark 2 */ 
#define  nag_regsn_mult_linear_add_var       g02dec  /* Mark 2 */ 
#define  nag_regsn_mult_linear_delete_var    g02dfc  /* Mark 2 */ 
#define  nag_regsn_mult_linear_newyvar       g02dgc  /* Mark 1 */ 
#define  nag_regsn_mult_linear_tran_model    g02dkc  /* Mark 2 */ 
#define  nag_regsn_mult_linear_est_func      g02dnc  /* Mark 2 */ 
#define  nag_regsn_std_resid_influence       g02fac  /* Mark 1 */ 
#define  nag_glm_normal                      g02gac  /* Mark 4 */ 
#define  nag_glm_binomial                    g02gbc  /* Mark 4 */ 
#define  nag_glm_poisson                     g02gcc  /* Mark 4 */ 
#define  nag_glm_gamma                       g02gdc  /* Mark 4 */ 
#define  nag_glm_tran_model                  g02gkc  /* Mark 4 */ 
#define  nag_glm_est_func                    g02gnc  /* Mark 4 */ 
#define  nag_robust_m_regsn_estim            g02hac  /* Mark 4 */ 
#define  nag_robust_corr_estim               g02hkc  /* Mark 4 */ 
#define  nag_mv_prin_comp                    g03aac  /* Mark 5 */ 
#define  nag_mv_canon_var                    g03acc  /* Mark 5 */ 
#define  nag_mv_canon_corr                   g03adc  /* Mark 5 */ 
#define  nag_mv_orthomax                     g03bac  /* Mark 5 */ 
#define  nag_mv_procustes                    g03bcc  /* Mark 5 */ 
#define  nag_mv_factor                       g03cac  /* Mark 5 */ 
#define  nag_mv_fac_score                    g03ccc  /* Mark 5 */ 
#define  nag_mv_discrim                      g03dac  /* Mark 5 */ 
#define  nag_mv_discrim_mahaldist            g03dbc  /* Mark 5 */ 
#define  nag_mv_discrim_group                g03dcc  /* Mark 5 */ 
#define  nag_mv_distance_mat                 g03eac  /* Mark 5 */ 
#define  nag_mv_hierar_cluster_analysis      g03ecc  /* Mark 5 */ 
#define  nag_mv_kmeans_cluster_analysis      g03efc  /* Mark 5 */ 
#define  nag_mv_dendrogram                   g03ehc  /* Mark 5 */ 
#define  nag_mv_cluster_indicator            g03ejc  /* Mark 5 */ 
#define  nag_mv_prin_coord_analysis          g03fac  /* Mark 5 */ 
#define  nag_mv_ordinal_multidimscale        g03fcc  /* Mark 5 */ 
#define  nag_mv_dend_free                    g03xzc  /* Mark 5 */ 
#define  nag_mv_z_scores                     g03zac  /* Mark 5 */ 
#define  nag_anova_random                    g04bbc  /* Mark 5 */ 
#define  nag_anova_factorial                 g04cac  /* Mark 5 */ 
#define  nag_anova_factorial_free            g04czc  /* Mark 5 */ 
#define  nag_random_continuous_uniform       g05cac  /* Mark 1 */ 
#define  nag_random_init_repeatable          g05cbc  /* Mark 1 */ 
#define  nag_random_init_nonrepeatable       g05ccc  /* Mark 1 */ 
#define  nag_save_random_state               g05cfc  /* Mark 1 */ 
#define  nag_restore_random_state            g05cgc  /* Mark 1 */ 
#define  nag_random_continuous_uniform_ab    g05dac  /* Mark 1 */ 
#define  nag_random_exp                      g05dbc  /* Mark 1 */ 
#define  nag_random_normal                   g05ddc  /* Mark 1 */ 
#define  nag_random_discrete_uniform         g05dyc  /* Mark 1 */ 
#define  nag_ref_vec_multi_normal            g05eac  /* Mark 2 */ 
#define  nag_ref_vec_poisson                 g05ecc  /* Mark 2 */ 
#define  nag_ref_vec_binomial                g05edc  /* Mark 2 */ 
#define  nag_ran_permut_vec                  g05ehc  /* Mark 3 */ 
#define  nag_ran_sample_vec                  g05ejc  /* Mark 3 */ 
#define  nag_ref_vec_discrete_pdf_cdf        g05exc  /* Mark 2 */ 
#define  nag_return_discrete                 g05eyc  /* Mark 2 */ 
#define  nag_return_multi_normal             g05ezc  /* Mark 2 */ 
#define  nag_random_beta                     g05fec  /* Mark 2 */ 
#define  nag_random_gamma                    g05ffc  /* Mark 2 */ 
#define  nag_arma_time_series                g05hac  /* Mark 3 */ 
#define  nag_2_sample_t_test                 g07cac  /* Mark 4 */ 
#define  nag_median_1var                     g07dac  /* Mark 3 */ 
#define  nag_robust_m_estim_1var             g07dbc  /* Mark 4 */ 
#define  nag_robust_trimmed_1var             g07ddc  /* Mark 4 */ 
#define  nag_running_median_smoother         g10cac  /* Mark 3 */ 
#define  nag_chi_sq_2_way_table              g11aac  /* Mark 4 */ 
#define  nag_prod_limit_surviv_fn            g12aac  /* Mark 4 */ 
#define  nag_tsa_auto_corr                   g13abc  /* Mark 2 */ 
#define  nag_tsa_auto_corr_part              g13acc  /* Mark 2 */ 
#define  nag_tsa_multi_inp_model_estim       g13bec  /* Mark 2 */ 
#define  nag_tsa_multi_inp_model_forecast    g13bjc  /* Mark 2 */ 
#define  nag_tsa_options_init                g13bxc  /* Mark 2 */ 
#define  nag_tsa_transf_orders               g13byc  /* Mark 2 */ 
#define  nag_tsa_trans_free                  g13bzc  /* Mark 2 doc, edited to correct form 3/8/93 */ 
#define  nag_tsa_spectrum_univar             g13cbc  /* Mark 4 */ 
#define  nag_tsa_spectrum_bivar              g13cdc  /* Mark 4 */ 
#define  nag_tsa_cross_spectrum_bivar        g13cec  /* Mark 4 */ 
#define  nag_tsa_gain_phase_bivar            g13cfc  /* Mark 4 */ 
#define  nag_tsa_noise_spectrum_bivar        g13cgc  /* Mark 4 */ 
#define  nag_kalman_sqrt_filt_cov_var        g13eac  /* Mark 3 */ 
#define  nag_kalman_sqrt_filt_cov_invar      g13ebc  /* Mark 3 */ 
#define  nag_kalman_sqrt_filt_info_var       g13ecc  /* Mark 3 */ 
#define  nag_kalman_sqrt_filt_info_invar     g13edc  /* Mark 3 */ 
#define  nag_trans_hessenberg_observer       g13ewc  /* Mark 3 */ 
#define  nag_trans_hessenberg_controller     g13exc  /* Mark 3 */ 
#define  nag_tsa_free                        g13xzc  /* Mark 2 doc, but replaced here 3 August 1993 */ 
#define  nag_ip_bb                           h02bbc  /* Mark 5 */ 
#define  nag_ip_mps_read                     h02buc  /* Mark 5 */ 
#define  nag_ip_mps_free                     h02bvc  /* Mark 5 */ 
#define  nag_ip_init                         h02xxc  /* Mark 5 */ 
#define  nag_ip_read                         h02xyc  /* Mark 5 */ 
#define  nag_ip_free                         h02xzc  /* Mark 5 */ 
#define  nag_transport                       h03abc  /* Mark 3 */ 
#define  nag_double_sort                     m01cac  /* Mark 1 */ 
#define  nag_quicksort                       m01csc  /* Mark 1 */ 
#define  nag_stable_sort                     m01ctc  /* Mark 1 */ 
#define  nag_chain_sort                      m01cuc  /* Mark 1 */ 
#define  nag_rank_sort                       m01dsc  /* Mark 1 */ 
#define  nag_reorder_vector                  m01esc  /* Mark 1 */ 
#define  nag_search_vector                   m01fsc  /* Mark 1 */ 
#define  nag_make_indices                    m01zac  /* Mark 1 */ 
#define  nag_tanh                            s10aac  /* Mark 1 */ 
#define  nag_sinh                            s10abc  /* Mark 1 */ 
#define  nag_cosh                            s10acc  /* Mark 1 */ 
#define  nag_arctanh                         s11aac  /* Mark 1 */ 
#define  nag_arcsinh                         s11abc  /* Mark 1 */ 
#define  nag_arccosh                         s11acc  /* Mark 1 */ 
#define  nag_exp_integral                    s13aac  /* Mark 1 */ 
#define  nag_cos_integral                    s13acc  /* Mark 1 */ 
#define  nag_sin_integral                    s13adc  /* Mark 1 */ 
#define  nag_gamma                           s14aac  /* Mark 1 */ 
#define  nag_log_gamma                       s14abc  /* Mark 1 */ 
#define  nag_incomplete_gamma                s14bac  /* Mark 2 */ 
#define  nag_cumul_normal                    s15abc  /* Mark 1 */ 
#define  nag_cumul_normal_complem            s15acc  /* Mark 1 */ 
#define  nag_erfc                            s15adc  /* Mark 1 */ 
#define  nag_erf                             s15aec  /* Mark 1 */ 
#define  nag_bessel_y0                       s17acc  /* Mark 1 */ 
#define  nag_bessel_y1                       s17adc  /* Mark 1 */ 
#define  nag_bessel_j0                       s17aec  /* Mark 1 */ 
#define  nag_bessel_j1                       s17afc  /* Mark 1 */ 
#define  nag_airy_ai                         s17agc  /* Mark 1 */ 
#define  nag_airy_bi                         s17ahc  /* Mark 1 */ 
#define  nag_airy_ai_deriv                   s17ajc  /* Mark 1 */ 
#define  nag_airy_bi_deriv                   s17akc  /* Mark 1 */ 
#define  nag_bessel_k0                       s18acc  /* Mark 1 */ 
#define  nag_bessel_k1                       s18adc  /* Mark 1 */ 
#define  nag_bessel_i0                       s18aec  /* Mark 1 */ 
#define  nag_bessel_i1                       s18afc  /* Mark 1 */ 
#define  nag_bessel_k0_scaled                s18ccc  /* Mark 2 */ 
#define  nag_bessel_k1_scaled                s18cdc  /* Mark 2 */ 
#define  nag_bessel_i0_scaled                s18cec  /* Mark 2 */ 
#define  nag_bessel_i1_scaled                s18cfc  /* Mark 2 */ 
#define  nag_kelvin_ber                      s19aac  /* Mark 1 */ 
#define  nag_kelvin_bei                      s19abc  /* Mark 1 */ 
#define  nag_kelvin_ker                      s19acc  /* Mark 1 */ 
#define  nag_kelvin_kei                      s19adc  /* Mark 1 */ 
#define  nag_fresnel_s                       s20acc  /* Mark 1 */ 
#define  nag_fresnel_c                       s20adc  /* Mark 1 */ 
#define  nag_elliptic_integral_rc            s21bac  /* Mark 1 */ 
#define  nag_elliptic_integral_rf            s21bbc  /* Mark 1 */ 
#define  nag_elliptic_integral_rd            s21bcc  /* Mark 1 */ 
#define  nag_elliptic_integral_rj            s21bdc  /* Mark 1 */ 
#define  nag_pi                              X01AAC  /* Mark 1 */ 
#define  nag_euler_constant                  X01ABC  /* Mark 1 */ 
#define  nag_max_sine_argument               X02AHC  /* Mark 1 */ 
#define  nag_machine_precision               X02AJC  /* Mark 1 */ 
#define  nag_real_smallest_number            X02AKC  /* Mark 1 */ 
#define  nag_real_largest_number             X02ALC  /* Mark 1 */ 
#define  nag_real_safe_small_number          X02AMC  /* Mark 1 */ 
#define  nag_max_integer                     X02BBC  /* Mark 1 */ 
#define  nag_decimal_digits                  X02BEC  /* Mark 1 */ 
#define  nag_real_base                       X02BHC  /* Mark 1 */ 
#define  nag_real_base_digits                X02BJC  /* Mark 1 */ 
#define  nag_real_min_exponent               X02BKC  /* Mark 1 */ 
#define  nag_real_max_exponent               X02BLC  /* Mark 1 */ 
#define  nag_active_set_size                 X02CAC  /* Mark 1 */ 
#define  nag_underflow_flag                  X02DAC  /* Mark 1 */ 
#define  nag_real_arithmetic_rounds          X02DJC  /* Mark 1 */ 


#endif  /* not NAG_NAMES */
