/* <nagex.h>
 *
 * Copyright 1997 Numerical Algorithms Group.
 *
 * Mark 5, 1997.
 *
 */

#include <nag.h>
#include <windows.h>

extern  int NAG_CALL a02bac_ex(char *resfile);
extern  int NAG_CALL c02afc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c02agc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c05adc_ex(char *resfile);
extern  int NAG_CALL c05nbc_ex(char *resfile);
extern  int NAG_CALL c05pbc_ex(char *resfile);
extern  int NAG_CALL c05sdc_ex(char *resfile);
extern  int NAG_CALL c05tbc_ex(char *resfile);
extern  int NAG_CALL c05ubc_ex(char *resfile);
extern  int NAG_CALL c05zbc_ex(char *resfile);
extern  int NAG_CALL c05zcc_ex(char *resfile);
extern  int NAG_CALL c06eac_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06ebc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06ecc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06ekc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06fpc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06fqc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06frc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06fuc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06gbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06gcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06gqc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06gsc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06gzc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06hac_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06hbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06hcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL c06hdc_ex(char *datafile, char *resfile);
extern  int NAG_CALL d01ajc_ex(char *resfile);
extern  int NAG_CALL d01akc_ex(char *resfile);
extern  int NAG_CALL d01alc_ex(char *resfile);
extern  int NAG_CALL d01amc_ex(char *resfile);
extern  int NAG_CALL d01anc_ex(char *resfile);
extern  int NAG_CALL d01apc_ex(char *resfile);
extern  int NAG_CALL d01aqc_ex(char *resfile);
extern  int NAG_CALL d01asc_ex(char *resfile);
extern  int NAG_CALL d01bac_ex(char *resfile);
extern  int NAG_CALL d01fcc_ex(char *resfile);
extern  int NAG_CALL d01gac_ex(char *datafile, char *resfile);
extern  int NAG_CALL d01gbc_ex(char *resfile);
extern  int NAG_CALL d01sjc_ex(char *resfile);
extern  int NAG_CALL d01skc_ex(char *resfile);
extern  int NAG_CALL d01slc_ex(char *resfile);
extern  int NAG_CALL d01smc_ex(char *resfile);
extern  int NAG_CALL d01snc_ex(char *resfile);
extern  int NAG_CALL d01spc_ex(char *resfile);
extern  int NAG_CALL d01sqc_ex(char *resfile);
extern  int NAG_CALL d01ssc_ex(char *resfile);
extern  int NAG_CALL d01tac_ex(char *resfile);
extern  int NAG_CALL d01wcc_ex(char *resfile);
extern  int NAG_CALL d01xbc_ex(char *resfile);
extern  int NAG_CALL d02cjc_ex(char *resfile);
extern  int NAG_CALL d02ejc_ex(char *resfile);
extern  int NAG_CALL d02gac_ex(char *resfile);
extern  int NAG_CALL d02gbc_ex(char *resfile);
extern  int NAG_CALL d02pcc_ex(char *resfile);
extern  int NAG_CALL d02pdc_ex(char *resfile);
extern  int NAG_CALL d02pwc_ex(char *resfile);
extern  int NAG_CALL d02pxc_ex(char *resfile);
extern  int NAG_CALL d02pzc_ex(char *resfile);
extern  int NAG_CALL d02qfc_ex(char *resfile);
extern  int NAG_CALL d02qzc_ex(char *resfile);
extern  int NAG_CALL d02rac_ex(char *resfile);
extern  int NAG_CALL e01bac_ex(char *resfile);
extern  int NAG_CALL e01bec_ex(char *datafile, char *resfile);
extern  int NAG_CALL e01bfc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e01bgc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e01bhc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e01dac_ex(char *datafile, char *resfile);
extern  int NAG_CALL e01sac_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02adc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02aec_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02afc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02bac_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02bbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02bcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02bdc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02bec_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02dcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02ddc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02dec_ex(char *datafile, char *resfile);
extern  int NAG_CALL e02dfc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04abc_ex(char *resfile);
extern  int NAG_CALL e04bbc_ex(char *resfile);
extern  int NAG_CALL e04ccc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04dgc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04fcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04gbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04hcc_ex(char *resfile);
extern  int NAG_CALL e04hdc_ex(char *resfile);
extern  int NAG_CALL e04jbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04kbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04lbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04mfc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04mzc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04ncc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04nfc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04nkc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04ucc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04unc_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04xac_ex(char *resfile);
extern  int NAG_CALL e04yac_ex(char *datafile, char *resfile);
extern  int NAG_CALL e04ycc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f01bnc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f01mcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f01qcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f01qdc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f01qec_ex(char *datafile, char *resfile);
extern  int NAG_CALL f01rcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f01rdc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f01rec_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02aac_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02abc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02adc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02aec_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02afc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02agc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02awc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02axc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02bjc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02ecc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02gcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02wec_ex(char *datafile, char *resfile);
extern  int NAG_CALL f02xec_ex(char *datafile, char *resfile);
extern  int NAG_CALL f03aec_ex(char *datafile, char *resfile);
extern  int NAG_CALL f03afc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f03ahc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f04adc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f04agc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f04ajc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f04akc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f04arc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f04awc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f04mcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f06pbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f06sbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f06ycc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f06zcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f11dac_ex(char *datafile, char *resfile);
extern  int NAG_CALL f11dcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f11dec_ex(char *datafile, char *resfile);
extern  int NAG_CALL f11jac_ex(char *datafile, char *resfile);
extern  int NAG_CALL f11jcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL f11jec_ex(char *datafile, char *resfile);
extern  int NAG_CALL f11zac_ex(char *datafile, char *resfile);
extern  int NAG_CALL f11zbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01aac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01alc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01bjc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01bkc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01blc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01cec_ex(char *resfile);
extern  int NAG_CALL g01ddc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01dhc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01eac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01ebc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01ecc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01edc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01eec_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01efc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01fac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01fbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01fcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01fdc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01fec_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01ffc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g01hac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02brc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02bxc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02cac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02cbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02dac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02dcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02ddc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02dec_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02dfc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02dgc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02dkc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02dnc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02fac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02gac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02gbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02gcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02gdc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02gkc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02gnc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02hac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g02hkc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03aac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03acc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03adc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03bac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03bcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03cac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03ccc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03dac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03dbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03dcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03eac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03ecc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03efc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03ehc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03ejc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03fac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03fcc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g03zac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g04bbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g04cac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g05cac_ex(char *resfile);
extern  int NAG_CALL g05cbc_ex(char *resfile);
extern  int NAG_CALL g05ccc_ex(char *resfile);
extern  int NAG_CALL g05cfc_ex(char *resfile);
extern  int NAG_CALL g05cgc_ex(char *resfile);
extern  int NAG_CALL g05dac_ex(char *resfile);
extern  int NAG_CALL g05dbc_ex(char *resfile);
extern  int NAG_CALL g05ddc_ex(char *resfile);
extern  int NAG_CALL g05dyc_ex(char *resfile);
extern  int NAG_CALL g05eac_ex(char *resfile);
extern  int NAG_CALL g05ecc_ex(char *resfile);
extern  int NAG_CALL g05edc_ex(char *resfile);
extern  int NAG_CALL g05ehc_ex(char *resfile);
extern  int NAG_CALL g05ejc_ex(char *resfile);
extern  int NAG_CALL g05exc_ex(char *resfile);
extern  int NAG_CALL g05eyc_ex(char *resfile);
extern  int NAG_CALL g05ezc_ex(char *resfile);
extern  int NAG_CALL g05fec_ex(char *resfile);
extern  int NAG_CALL g05ffc_ex(char *resfile);
extern  int NAG_CALL g05hac_ex(char *resfile);
extern  int NAG_CALL g07cac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g07dac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g07dbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g07ddc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g10cac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g11aac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g12aac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13abc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13acc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13bec_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13bjc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13cac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13cbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13ccc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13cdc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13cec_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13cfc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13cgc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13eac_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13ebc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13ecc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13edc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13ewc_ex(char *datafile, char *resfile);
extern  int NAG_CALL g13exc_ex(char *datafile, char *resfile);
extern  int NAG_CALL h02bbc_ex(char *datafile, char *resfile);
extern  int NAG_CALL h02buc_ex(char *datafile, char *resfile);
extern  int NAG_CALL h03abc_ex(char *resfile);
extern  int NAG_CALL m01cac_ex(char *datafile, char *resfile);
extern  int NAG_CALL m01csc_ex(char *datafile, char *resfile);
extern  int NAG_CALL m01ctc_ex(char *datafile, char *resfile);
extern  int NAG_CALL m01cuc_ex(char *resfile);
extern  int NAG_CALL m01dsc_ex(char *datafile, char *resfile);
extern  int NAG_CALL m01esc_ex(char *datafile, char *resfile);
extern  int NAG_CALL m01fsc_ex(char *datafile, char *resfile);
extern  int NAG_CALL m01zac_ex(char *datafile, char *resfile);
extern  int NAG_CALL s10aac_ex(char *datafile, char *resfile);
extern  int NAG_CALL s10abc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s10acc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s11aac_ex(char *datafile, char *resfile);
extern  int NAG_CALL s11abc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s11acc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s13aac_ex(char *datafile, char *resfile);
extern  int NAG_CALL s13acc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s13adc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s14aac_ex(char *datafile, char *resfile);
extern  int NAG_CALL s14abc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s14bac_ex(char *datafile, char *resfile);
extern  int NAG_CALL s15abc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s15acc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s15adc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s15aec_ex(char *datafile, char *resfile);
extern  int NAG_CALL s17acc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s17adc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s17aec_ex(char *datafile, char *resfile);
extern  int NAG_CALL s17afc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s17agc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s17ahc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s17ajc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s17akc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s18acc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s18adc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s18aec_ex(char *datafile, char *resfile);
extern  int NAG_CALL s18afc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s18ccc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s18cdc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s18cec_ex(char *datafile, char *resfile);
extern  int NAG_CALL s18cfc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s19aac_ex(char *datafile, char *resfile);
extern  int NAG_CALL s19abc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s19acc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s19adc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s20acc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s20adc_ex(char *datafile, char *resfile);
extern  int NAG_CALL s21bac_ex(char *resfile);
extern  int NAG_CALL s21bbc_ex(char *resfile);
extern  int NAG_CALL s21bcc_ex(char *resfile);
extern  int NAG_CALL s21bdc_ex(char *resfile);
