#ifndef NAGLX03
#define NAGLX03

/* <naglx03.h>
 *
 * Copyright 1991 Numerical Algorithms Group
 *
 * Local include file for NAG C Library x03 chapter
 *
 * This header file was generated by getcons.
 *
 * Mark 2, 1991
 */

/*
 ********** Implementation-dependent constant **********
 *
 * X03AAY_CONS must be set to  b**(t - int(t/2)) + 1 ,
 * where t is the number of b-ary digits in the mantissa
 * of a double precision number.
 * For b = 16 and t = 14 (e.g. IBM 370), or
 * for b = 2 and t = 56 (e.g. DEC VAX-11)
 * X03AAY_CONS = 268435457.0e0
 * For IEEE machines (e.g. Apollo)
 * X03AAY_CONS = 134217729.0e0
 *
 *******************************************************
 */

#define X03AAY_CONS 134217729.0

/*
 * The following define should be activated for
 * those machines where arithmetic is not carried out in
 * extra-precise registers, or where a compiler option
 * can be used to force this.
 * If X03AAY_CONSISTENT_ARITH can be defined, the
 * x03 routines will run faster.
 */

#define X03AAY_CONSISTENT_ARITH

#endif  /* not NAGLX03 */
