#ifndef NAGX02
#define NAGX02
#ifdef __cplusplus
extern "C"
{
#endif

/* <nagx02.h>
 *
 * Copyright 1991 Numerical Algorithms Group.
 *
 * Header file for the x02 chapter of the NAG C Library.
 * Definitions of machine-specific constants.
 *
 * This header file was generated by getcons.
 *
 * Mark 5, 1998
 *
 */

#define X02AHC x02ahc()
#define X02AJC x02ajc()
#define X02AKC x02akc()
#define X02ALC x02alc()
#define X02AMC x02amc()

#ifdef NAG_PROTO
  extern NAG_DLL_EXPIMP double NAG_CALL x02ahc(void);
  extern NAG_DLL_EXPIMP double NAG_CALL x02ajc(void);
  extern NAG_DLL_EXPIMP double NAG_CALL x02akc(void);
  extern NAG_DLL_EXPIMP double NAG_CALL x02alc(void);
  extern NAG_DLL_EXPIMP double NAG_CALL x02amc(void);
  extern void x02zaz(double wmach[]);
#else
  extern double x02ahc();
  extern double x02ajc();
  extern double x02akc();
  extern double x02alc();
  extern double x02amc();
  extern void x02zaz();
#endif

#define X02BBC 2147483647
#define X02BEC 15
#define X02BHC 2
#define X02BJC 53
#define X02BKC -1021
#define X02BLC 1024
#define X02DAC FALSE
#define X02DJC TRUE

#ifdef __cplusplus
}
#endif
#endif  /* not NAGX02 */
