#ifndef ARM_SWAP_H
#define ARM_SWAP_H



#include "ARM_result.h"



extern long ARM_LIBORSWAP (double StartDate,
						   double EndDate,
						   long LiborType,
						   long ReceiveOrPay,
						   double FixedRate,
						   double Spread, 
						   long CcyId,
						   ARM_result& result,
						   long objId = -1);

extern long ARM_SWAPLEG (long irIndex,
						 double startDate,
						 double endDate,
						 long receiveOrPay,
						 long spreadType,
						 double spread,
						 long ccyId,
						 long dayCount,
						 long resetGap,
						 CCString resetCal,
						 CCString payCal,
						 long decompPricingFlag,
                         long nxChange,
						 long stubRuleId,
						 double refDate,
						 ARM_result& result,
						 long objId = -1);

extern long ARM_SWAP_PRICE_TO_RATE (long sId,
									double Date,
						            double Price,
									long modId,
						            ARM_result& result);

extern long ARM_SWAP_RATE_TO_PRICE (long sId,
									double date,
						            double rate,
									long modId,
						            ARM_result& result);

extern long ARM_FIXEDLEG(double startDate,
						 double endDate,
						 long receiveOrPay, 
						 long fixedRateType,
						 double fixedRate,
						 long dayCount,
						 long freq,
						 long decompFreq,
						 long payTiming,
						 long intRule,
						 long stubRule,
						 long ccyId,
						 CCString payCalName,
                         long nxChange,
						 double refDate,
						 ARM_result& result,
						 long objId = -1);

extern long ARM_LIBORLEG (double startDate,
						  double endDate,
						  long liborType,
						  long receiveOrPay,
						  long spreadType,
						  double spread,
						  long resetFreq,
						  long payFreq,
						  long resetTiming,
						  long payTiming,
						  long ccyId,
						  long intRuleId,
						  long resetGap,
						  CCString resetCal,
						  CCString payCal,
						  long decompPricingFlag,
                          long nxChange,
						  long stubRuleId,
						  double refDate,
						  ARM_result& result,
						  long objId = -1);

extern long ARM_TMLEG (long tmIxType,
					   double startDate,
					   double endDate,
					   long receiveOrPay,
					   double spread,
					   ARM_result& result,
					   long objId = -1);

extern long ARM_SwapFromSummit (const CCString& swapId,
								long zcId,
								ARM_result& result,
								long objId = -1);

extern long ARM_IMPLIEDSPREAD (long swapId,
							   long modelId,
							   double price,
							   long leg1Or2,
							   ARM_result& result);

extern long ARM_IMPLIEDSPREADWITHMODELS (long swapId,
										 long modelId1,
										 long modelId2,
										 double price,
							             long leg1Or2,
										 ARM_result& result);

extern long ARM_GEN_SWAP (const CCString& delivery,
						  long liborTypeId,
						  const CCString& ccy,
						  ARM_result& result,
						  long objId = -1);

extern long ARM_CMTLEG(double startDate,
					   double endDate,
					   long cmtTypeId,
					   long bondCouponFreq,
					   long bondDayCount,
					   long receiveOrPay,
					   double spread,
					   long yieldDecompFreq,
					   long swapLegDayCount,
					   long intRule,
					   long resetGap,
					   long resetFreq,
					   double ntlAmount,
					   long ccyId,
                       long resetTiming,
                       ARM_result& result,
					   long objId = -1);

extern long ARM_CMSLEG (double startDate,
						double endDate,
						long cmsTypeId,
						long receiveOrPay,
						double spread,
						long yieldDecompFreq,
						long swapLegDayCount,
						long resetFreq,
						long intRule,
						long ccyId,
						long resetTiming,
						ARM_result& result,
						long objId = -1);

extern long ARM_SWAP (long swapLeg1,
					  long swapLeg2,
					  long minPay,
					  ARM_result& result,
					  long objId = -1);

extern long ARM_SWAP_WITH_NOTIONNAL (long swapLeg1,
									 long swapLeg2,
									 long notId,
									 long minPay,
									 ARM_result& result,
									 long objId = -1);

extern long ARM_FIXRATES (double swapLegId,
						  VECTOR<double>& rate,
				          ARM_result& result,
						  long objId = -1);

extern long ARM_LiborAssetSwapMargin (long modelId,
									  double startDate,
									  double endDate,
							          double fixedRate,
									  long fixReceiveOrPayId, 
									  long fixDayCountId,
									  long fixFrequencyId,
									  long fixDecompFrequencyId,
									  long fixPayTimingId,
									  long fixIntRuleId,
									  long liborTypeId,
									  double spread,
									  long floatResetFreqId,
									  long floatPayFreqId,
									  long assetGap,
									  long vFlag,
									  double price,
									  const CCString& discountCCy,
									  double redemptionPrice,
									  double supplFee,
									  long solve,
									  const CCString& id,
									  ARM_result& result);

extern long ARM_LiborAssetSwapPrice (long modelId,
									 double startDate,
									 double endDate,
									 double fixedRate,
									 long fixReceiveOrPayId,
				  					 long fixDayCountId,
									 long fixFrequencyId,
									 long fixDecompFrequencyId,
									 long fixPayTimingId,
									 long fixIntRuleId,
									 long liborTypeId,
									 double spread,
									 long floatResetFreqId,
									 long floatPayFreqId,
									 long assetGap,
									 long vFlag,
									 double margin,
									 const CCString& discountCcy,
									 double redemptionPrice,
									 double supplFee,
									 long solve,
									 const CCString& id,
									 double minValue,
									 double maxValue,
									 ARM_result& result);

extern long ARM_RESTRIKABLELEG(double startDate,
							   double endDate,
				               long receiveOrPay,
							   long payIndexId,
				               long payFreq,
							   double spread, 
                               long refIndexId,
							   long resetFreq,
				               long resetTiming,
							   long payTiming, 
                               long stubRule,
                               double range,
							   long rangeSpec,
				               long ccyId,
							   long MCFreq,
							   long MCInterp,
                               long decompPricingFlag,
                               ARM_result& result, 
                               long objId = -1);

extern long ARM_CORRIDORLEG(double startDate,
							double endDate,
							long receiveOrPay,
							long payIndexId,
							long payFreq,
							long spreadType,
							double spread,
							long refIndexId,
							long resetFreq,
							long paidRateResetTiming,
							long refRateResetTiming,
							long stubRule,
							long levelDownId,
							long downSpec,
							long levelUpId,
							long upSpec,
							long ccyId,
							long MCFreq,
							long MCInterp,
							long LDPricingMethod,
                            long decompPricingFlag,
							ARM_result& result,
							long objId = -1);

extern long ARM_REVERSEFLOAT(double startDate,
							 double endDate,
							 double NotionalRatio,
							 long receiveOrPay,
							 long liborType,
							 const CCString& fltccy,
							 long fltSpreadsId,
							 long extraSpreadFixId,
							 long fltDayCount,
							 long fxCouponsId,
							 const CCString& reverseCcy,
							 long payFreq,
							 long reverseIndexId,
							 long fxDayCount,
							 double multiplier,
							 double couponFloor,
							 double stubDate,
							 ARM_result& result,
							 long objId = -1);

extern long ARM_IMPLIED_RANGE (long restrikableId,
							   long modelId,
							   double price,
							   ARM_result& result);

extern long ARM_ARM_GenAmortization (long swaplegId,
									 long amortMethodId,
									 long amortFrequency,
									 double amortAmount,
									 long daycountId,
									 double legNotional,
									 double amortRate,
									 double reducedMaturity,
									 long modelId,
									 double percentOfRemainder,
									 ARM_result& result,
									 long objId = -1);

extern long ARM_ARM_CUSTOMFSTCPN (long swlegId,
								  double date,
								  ARM_result& result);

#endif	// ARM_SWAP_H

/*----End Of File ----*/
